ABILITY_DICT = {
	"Bulbasaur": ["Chlorophyll"],
	"Ivysaur": ["Chlorophyll"],
	"Venusaur": ["Chlorophyll"],
	"Charmander": ["Solar Power"],
	"Charmeleon": ["Solar Power"],
	"Charizard": ["Solar Power"],
	"Squirtle": ["Rain Dish"],
	"Wartortle": ["Rain Dish"],
	"Blastoise": ["Rain Dish"],
	"Caterpie": ["Run Away"],
	"Butterfree": ["Tinted Lens"],
	"Weedle": ["Run Away"],
	"Beedrill": ["Sniper"],
	"Pidgey": ["Big Pecks"],
	"Pidgeotto": ["Big Pecks"],
	"Pidgeot": ["Big Pecks"],
	"Rattata": ["Hustle", "Thick Fat"],
	"Raticate": ["Hustle", "Thick Fat"],
	"Spearow": ["Sniper"],
	"Fearow": ["Sniper"],
	"Ekans": ["Unnerve"],
	"Arbok": ["Unnerve"],
	"Pichu": ["Lightning Rod"],
	"Pikachu": ["Lightning Rod"],
	"Raichu": ["Lightning Rod"],
	"Sandshrew": ["Sand Rush", "Slush Rush"],
	"Sandslash": ["Sand Rush", "Slush Rush"],
	"Nidoran♀": ["Hustle"],
	"Nidorina": ["Hustle"],
	"Nidoqueen": ["Sheer Force"],
	"Nidoran♂": ["Hustle"],
	"Nidorino": ["Hustle"],
	"Nidoking": ["Sheer Force"],
	"Cleffa": ["Friend Guard"],
	"Clefairy": ["Friend Guard"],
	"Clefable": ["Unaware"],
	"Vulpix": ["Drought", "Snow Warning"],
	"Ninetales": ["Drought", "Snow Warning"],
	"Igglybuff": ["Friend Guard"],
	"Jigglypuff": ["Friend Guard"],
	"Wigglytuff": ["Frisk"],
	"Zubat": ["Infiltrator"],
	"Golbat": ["Infiltrator"],
	"Crobat": ["Infiltrator"],
	"Oddish": ["Run Away"],
	"Gloom": ["Stench"],
	"Vileplume": ["Effect Spore"],
	"Bellossom": ["Healer"],
	"Paras": ["Damp"],
	"Parasect": ["Damp"],
	"Venonat": ["Run Away"],
	"Venomoth": ["Wonder Skin"],
	"Diglett": ["Sand Force"],
	"Dugtrio": ["Sand Force"],
	"Meowth": ["Unnerve", "Rattled"],
	"Persian": ["Unnerve", "Rattled"],
	"Perrserker": ["Steely Spirit"],
	"Psyduck": ["Swift Swim"],
	"Golduck": ["Swift Swim"],
	"Mankey": ["Defiant"],
	"Primeape": ["Defiant"],
	"Annihilape": ["Defiant"],
	"Growlithe": ["Justified", "Rock Head"],
	"Arcanine": ["Justified", "Rock Head"],
	"Poliwag": ["Swift Swim"],
	"Poliwhirl": ["Swift Swim"],
	"Poliwrath": ["Swift Swim"],
	"Politoed": ["Drizzle"],
	"Abra": ["Magic Guard"],
	"Kadabra": ["Magic Guard"],
	"Alakazam": ["Magic Guard"],
	"Machop": ["Steadfast"],
	"Machoke": ["Steadfast"],
	"Machamp": ["Steadfast"],
	"Bellsprout": ["Gluttony"],
	"Weepinbell": ["Gluttony"],
	"Victreebel": ["Gluttony"],
	"Tentacool": ["Rain Dish"],
	"Tentacruel": ["Rain Dish"],
	"Geodude": ["Sand Veil", "Galvanize"],
	"Graveler": ["Sand Veil", "Galvanize"],
	"Golem": ["Sand Veil", "Galvanize"],
	"Ponyta": ["Flame Body", "Anticipation"],
	"Rapidash": ["Flame Body", "Anticipation"],
	"Slowpoke": ["Regenerator"],
	"Slowbro": ["Regenerator"],
	"Slowking": ["Regenerator"],
	"Magnemite": ["Analytic"],
	"Magneton": ["Analytic"],
	"Magnezone": ["Analytic"],
	"Farfetch'd": ["Defiant", "Scrappy"],
	"Sirfetch'd": ["Scrappy"],
	"Doduo": ["Tangled Feet"],
	"Dodrio": ["Tangled Feet"],
	"Seel": ["Ice Body"],
	"Dewgong": ["Ice Body"],
	"Grimer": ["Poison Touch", "Power of Alchemy"],
	"Muk": ["Poison Touch", "Power of Alchemy"],
	"Shellder": ["Overcoat"],
	"Cloyster": ["Overcoat"],
	"Onix": ["Weak Armor"],
	"Steelix": ["Sheer Force"],
	"Drowzee": ["Inner Focus"],
	"Hypno": ["Inner Focus"],
	"Krabby": ["Sheer Force"],
	"Kingler": ["Sheer Force"],
	"Voltorb": ["Aftermath"],
	"Electrode": ["Aftermath"],
	"Exeggcute": ["Harvest"],
	"Exeggutor": ["Harvest"],
	"Cubone": ["Battle Armor"],
	"Marowak": ["Battle Armor", "Rock Head"],
	"Tyrogue": ["Vital Spirit"],
	"Hitmonlee": ["Unburden"],
	"Hitmonchan": ["Inner Focus"],
	"Hitmontop": ["Steadfast"],
	"Lickitung": ["Cloud Nine"],
	"Lickilicky": ["Cloud Nine"],
	"Koffing": ["Stench"],
	"Weezing": ["Stench", "Misty Surge"],
	"Rhyhorn": ["Reckless"],
	"Rhydon": ["Reckless"],
	"Rhyperior": ["Reckless"],
	"Happiny": ["Friend Guard"],
	"Chansey": ["Healer"],
	"Blissey": ["Healer"],
	"Tangela": ["Regenerator"],
	"Tangrowth": ["Regenerator"],
	"Kangaskhan": ["Inner Focus"],
	"Horsea": ["Damp"],
	"Seadra": ["Damp"],
	"Kingdra": ["Damp"],
	"Goldeen": ["Lightning Rod"],
	"Seaking": ["Lightning Rod"],
	"Staryu": ["Analytic"],
	"Starmie": ["Analytic"],
	"Mime Jr.": ["Technician"],
	"Mr. Mime": ["Technician", "Ice Body"],
	"Mr. Rime": ["Ice Body"],
	"Scyther": ["Steadfast"],
	"Scizor": ["Light Metal"],
	"Kleavor": ["Sharpness"],
	"Smoochum": ["Hydration"],
	"Jynx": ["Dry Skin"],
	"Elekid": ["Vital Spirit"],
	"Electabuzz": ["Vital Spirit"],
	"Electivire": ["Vital Spirit"],
	"Magby": ["Vital Spirit"],
	"Magmar": ["Vital Spirit"],
	"Magmortar": ["Vital Spirit"],
	"Pinsir": ["Moxie"],
	"Tauros": ["Sheer Force", "Cud Chew"],
	"Magikarp": ["Rattled"],
	"Gyarados": ["Moxie"],
	"Lapras": ["Hydration"],
	"Ditto": ["Imposter"],
	"Eevee": ["Anticipation"],
	"Vaporeon": ["Hydration"],
	"Jolteon": ["Quick Feet"],
	"Flareon": ["Guts"],
	"Espeon": ["Magic Bounce"],
	"Umbreon": ["Inner Focus"],
	"Leafeon": ["Chlorophyll"],
	"Glaceon": ["Ice Body"],
	"Sylveon": ["Pixilate"],
	"Porygon": ["Analytic"],
	"Porygon2": ["Analytic"],
	"Porygon-Z": ["Analytic"],
	"Omanyte": ["Weak Armor"],
	"Omastar": ["Weak Armor"],
	"Kabuto": ["Weak Armor"],
	"Kabutops": ["Weak Armor"],
	"Aerodactyl": ["Unnerve"],
	"Munchlax": ["Gluttony"],
	"Snorlax": ["Gluttony"],
	"Articuno": ["Snow Cloak"],
	"Zapdos": ["Static"],
	"Moltres": ["Flame Body"],
	"Dratini": ["Marvel Scale"],
	"Dragonair": ["Marvel Scale"],
	"Dragonite": ["Multiscale"],
	"Mewtwo": ["Unnerve"],
	"Chikorita": ["Leaf Guard"],
	"Bayleef": ["Leaf Guard"],
	"Meganium": ["Leaf Guard"],
	"Cyndaquil": ["Flash Fire"],
	"Quilava": ["Flash Fire"],
	"Typhlosion": ["Flash Fire", "Frisk"],
	"Totodile": ["Sheer Force"],
	"Croconaw": ["Sheer Force"],
	"Feraligatr": ["Sheer Force"],
	"Sentret": ["Frisk"],
	"Furret": ["Frisk"],
	"Hoothoot": ["Tinted Lens"],
	"Noctowl": ["Tinted Lens"],
	"Ledyba": ["Rattled"],
	"Ledian": ["Iron Fist"],
	"Spinarak": ["Sniper"],
	"Ariados": ["Sniper"],
	"Chinchou": ["Water Absorb"],
	"Lanturn": ["Water Absorb"],
	"Togepi": ["Super Luck"],
	"Togetic": ["Super Luck"],
	"Togekiss": ["Super Luck"],
	"Natu": ["Magic Bounce"],
	"Xatu": ["Magic Bounce"],
	"Mareep": ["Plus"],
	"Flaaffy": ["Plus"],
	"Ampharos": ["Plus"],
	"Azurill": ["Sap Sipper"],
	"Marill": ["Sap Sipper"],
	"Azumarill": ["Sap Sipper"],
	"Bonsly": ["Rattled"],
	"Sudowoodo": ["Rattled"],
	"Hoppip": ["Infiltrator"],
	"Skiploom": ["Infiltrator"],
	"Jumpluff": ["Infiltrator"],
	"Aipom": ["Skill Link"],
	"Ambipom": ["Skill Link"],
	"Sunkern": ["Early Bird"],
	"Sunflora": ["Early Bird"],
	"Yanma": ["Frisk"],
	"Yanmega": ["Frisk"],
	"Wooper": ["Unaware"],
	"Quagsire": ["Unaware"],
	"Clodsire": ["Unaware"],
	"Murkrow": ["Prankster"],
	"Honchkrow": ["Moxie"],
	"Wynaut": ["Telepathy"],
	"Wobbuffet": ["Telepathy"],
	"Girafarig": ["Sap Sipper"],
	"Farigiraf": ["Sap Sipper"],
	"Pineco": ["Overcoat"],
	"Forretress": ["Overcoat"],
	"Dunsparce": ["Rattled"],
	"Dudunsparce": ["Rattled"],
	"Gligar": ["Immunity"],
	"Gliscor": ["Poison Heal"],
	"Snubbull": ["Rattled"],
	"Granbull": ["Rattled"],
	"Qwilfish": ["Intimidate"],
	"Overqwil": ["Intimidate"],
	"Shuckle": ["Contrary"],
	"Heracross": ["Moxie"],
	"Sneasel": ["Pickpocket"],
	"Weavile": ["Pickpocket"],
	"Sneasler": ["Poison Touch"],
	"Teddiursa": ["Honey Gather"],
	"Ursaring": ["Unnerve"],
	"Ursaluna": ["Unnerve"],
	"Slugma": ["Weak Armor"],
	"Magcargo": ["Weak Armor"],
	"Swinub": ["Thick Fat"],
	"Piloswine": ["Thick Fat"],
	"Mamoswine": ["Thick Fat"],
	"Corsola": ["Regenerator", "Cursed Body"],
	"Cursola": ["Perish Body"],
	"Remoraid": ["Moody"],
	"Octillery": ["Moody"],
	"Delibird": ["Insomnia"],
	"Mantyke": ["Water Veil"],
	"Mantine": ["Water Veil"],
	"Skarmory": ["Weak Armor"],
	"Houndour": ["Unnerve"],
	"Houndoom": ["Unnerve"],
	"Phanpy": ["Sand Veil"],
	"Donphan": ["Sand Veil"],
	"Stantler": ["Sap Sipper"],
	"Wyrdeer": ["Sap Sipper"],
	"Smeargle": ["Moody"],
	"Miltank": ["Sap Sipper"],
	"Raikou": ["Inner Focus"],
	"Entei": ["Inner Focus"],
	"Suicune": ["Inner Focus"],
	"Larvitar": ["Sand Veil"],
	"Tyranitar": ["Unnerve"],
	"Lugia": ["Multiscale"],
	"Ho-Oh": ["Regenerator"],
	"Treecko": ["Unburden"],
	"Grovyle": ["Unburden"],
	"Sceptile": ["Unburden"],
	"Torchic": ["Speed Boost"],
	"Combusken": ["Speed Boost"],
	"Blaziken": ["Speed Boost"],
	"Mudkip": ["Damp"],
	"Marshtomp": ["Damp"],
	"Swampert": ["Damp"],
	"Poochyena": ["Rattled"],
	"Mightyena": ["Moxie"],
	"Zigzagoon": ["Quick Feet"],
	"Linoone": ["Quick Feet"],
	"Obstagoon": ["Defiant"],
	"Wurmple": ["Run Away"],
	"Beautifly": ["Rivalry"],
	"Dustox": ["Compound Eyes"],
	"Lotad": ["Own Tempo"],
	"Lombre": ["Own Tempo"],
	"Ludicolo": ["Own Tempo"],
	"Seedot": ["Pickpocket"],
	"Nuzleaf": ["Pickpocket"],
	"Shiftry": ["Pickpocket"],
	"Taillow": ["Scrappy"],
	"Swellow": ["Scrappy"],
	"Wingull": ["Rain Dish"],
	"Pelipper": ["Rain Dish"],
	"Ralts": ["Telepathy"],
	"Kirlia": ["Telepathy"],
	"Gardevoir": ["Telepathy"],
	"Gallade": ["Justified"],
	"Surskit": ["Rain Dish"],
	"Masquerain": ["Unnerve"],
	"Shroomish": ["Quick Feet"],
	"Breloom": ["Technician"],
	"Nincada": ["Run Away"],
	"Ninjask": ["Infiltrator"],
	"Whismur": ["Rattled"],
	"Loudred": ["Scrappy"],
	"Exploud": ["Scrappy"],
	"Makuhita": ["Sheer Force"],
	"Hariyama": ["Sheer Force"],
	"Nosepass": ["Sand Force"],
	"Probopass": ["Sand Force"],
	"Skitty": ["Wonder Skin"],
	"Delcatty": ["Wonder Skin"],
	"Sableye": ["Prankster"],
	"Mawile": ["Sheer Force"],
	"Aron": ["Heavy Metal"],
	"Lairon": ["Heavy Metal"],
	"Aggron": ["Heavy Metal"],
	"Meditite": ["Telepathy"],
	"Medicham": ["Telepathy"],
	"Electrike": ["Minus"],
	"Manectric": ["Minus"],
	"Plusle": ["Lightning Rod"],
	"Minun": ["Volt Absorb"],
	"Volbeat": ["Prankster"],
	"Illumise": ["Prankster"],
	"Budew": ["Leaf Guard"],
	"Roselia": ["Leaf Guard"],
	"Roserade": ["Technician"],
	"Gulpin": ["Gluttony"],
	"Swalot": ["Gluttony"],
	"Carvanha": ["Speed Boost"],
	"Sharpedo": ["Speed Boost"],
	"Wailmer": ["Pressure"],
	"Wailord": ["Pressure"],
	"Numel": ["Own Tempo"],
	"Camerupt": ["Anger Point"],
	"Torkoal": ["Shell Armor"],
	"Spoink": ["Gluttony"],
	"Grumpig": ["Gluttony"],
	"Spinda": ["Contrary"],
	"Trapinch": ["Sheer Force"],
	"Cacnea": ["Water Absorb"],
	"Cacturne": ["Water Absorb"],
	"Swablu": ["Cloud Nine"],
	"Altaria": ["Cloud Nine"],
	"Zangoose": ["Toxic Boost"],
	"Seviper": ["Infiltrator"],
	"Barboach": ["Hydration"],
	"Whiscash": ["Hydration"],
	"Corphish": ["Adaptability"],
	"Crawdaunt": ["Adaptability"],
	"Lileep": ["Storm Drain"],
	"Cradily": ["Storm Drain"],
	"Anorith": ["Swift Swim"],
	"Armaldo": ["Swift Swim"],
	"Feebas": ["Adaptability"],
	"Milotic": ["Cute Charm"],
	"Kecleon": ["Protean"],
	"Shuppet": ["Cursed Body"],
	"Banette": ["Cursed Body"],
	"Duskull": ["Frisk"],
	"Dusclops": ["Frisk"],
	"Dusknoir": ["Frisk"],
	"Tropius": ["Harvest"],
	"Absol": ["Justified"],
	"Snorunt": ["Moody"],
	"Glalie": ["Moody"],
	"Froslass": ["Cursed Body"],
	"Spheal": ["Oblivious"],
	"Sealeo": ["Oblivious"],
	"Walrein": ["Oblivious"],
	"Clamperl": ["Rattled"],
	"Huntail": ["Water Veil"],
	"Gorebyss": ["Hydration"],
	"Relicanth": ["Sturdy"],
	"Luvdisc": ["Hydration"],
	"Bagon": ["Sheer Force"],
	"Shelgon": ["Overcoat"],
	"Salamence": ["Moxie"],
	"Beldum": ["Light Metal"],
	"Metang": ["Light Metal"],
	"Metagross": ["Light Metal"],
	"Regirock": ["Sturdy"],
	"Regice": ["Ice Body"],
	"Registeel": ["Light Metal"],
	"Turtwig": ["Shell Armor"],
	"Grotle": ["Shell Armor"],
	"Torterra": ["Shell Armor"],
	"Chimchar": ["Iron Fist"],
	"Monferno": ["Iron Fist"],
	"Infernape": ["Iron Fist"],
	"Piplup": ["Competitive"],
	"Prinplup": ["Competitive"],
	"Empoleon": ["Competitive"],
	"Starly": ["Reckless"],
	"Staravia": ["Reckless"],
	"Staraptor": ["Reckless"],
	"Bidoof": ["Moody"],
	"Bibarel": ["Moody"],
	"Kricketot": ["Run Away"],
	"Kricketune": ["Technician"],
	"Shinx": ["Guts"],
	"Luxio": ["Guts"],
	"Luxray": ["Guts"],
	"Cranidos": ["Sheer Force"],
	"Rampardos": ["Sheer Force"],
	"Shieldon": ["Soundproof"],
	"Bastiodon": ["Soundproof"],
	"Burmy": ["Overcoat"],
	"Wormadam": ["Overcoat"],
	"Mothim": ["Tinted Lens"],
	"Combee": ["Hustle"],
	"Vespiquen": ["Unnerve"],
	"Pachirisu": ["Volt Absorb"],
	"Buizel": ["Water Veil"],
	"Floatzel": ["Water Veil"],
	"Shellos": ["Sand Force"],
	"Gastrodon": ["Sand Force"],
	"Drifloon": ["Flare Boost"],
	"Drifblim": ["Flare Boost"],
	"Buneary": ["Limber"],
	"Lopunny": ["Limber"],
	"Glameow": ["Keen Eye"],
	"Purugly": ["Defiant"],
	"Stunky": ["Keen Eye"],
	"Skuntank": ["Keen Eye"],
	"Bronzor": ["Heavy Metal"],
	"Bronzong": ["Heavy Metal"],
	"Chatot": ["Big Pecks"],
	"Spiritomb": ["Infiltrator"],
	"Gible": ["Rough Skin"],
	"Gabite": ["Rough Skin"],
	"Garchomp": ["Rough Skin"],
	"Riolu": ["Prankster"],
	"Lucario": ["Justified"],
	"Hippopotas": ["Sand Force"],
	"Hippowdon": ["Sand Force"],
	"Skorupi": ["Keen Eye"],
	"Drapion": ["Keen Eye"],
	"Croagunk": ["Poison Touch"],
	"Toxicroak": ["Poison Touch"],
	"Finneon": ["Water Veil"],
	"Lumineon": ["Water Veil"],
	"Snover": ["Soundproof"],
	"Abomasnow": ["Soundproof"],
	"Dialga": ["Telepathy"],
	"Palkia": ["Telepathy"],
	"Heatran": ["Flame Body"],
	"Giratina": ["Telepathy"],
	"Snivy": ["Contrary"],
	"Servine": ["Contrary"],
	"Serperior": ["Contrary"],
	"Tepig": ["Thick Fat"],
	"Pignite": ["Thick Fat"],
	"Emboar": ["Reckless"],
	"Oshawott": ["Shell Armor"],
	"Dewott": ["Shell Armor"],
	"Samurott": ["Shell Armor", "Sharpness"],
	"Patrat": ["Analytic"],
	"Watchog": ["Analytic"],
	"Lillipup": ["Run Away"],
	"Herdier": ["Scrappy"],
	"Stoutland": ["Scrappy"],
	"Purrloin": ["Prankster"],
	"Liepard": ["Prankster"],
	"Pansage": ["Overgrow"],
	"Simisage": ["Overgrow"],
	"Pansear": ["Blaze"],
	"Simisear": ["Blaze"],
	"Panpour": ["Torrent"],
	"Simipour": ["Torrent"],
	"Munna": ["Telepathy"],
	"Musharna": ["Telepathy"],
	"Pidove": ["Rivalry"],
	"Tranquill": ["Rivalry"],
	"Unfezant": ["Rivalry"],
	"Blitzle": ["Sap Sipper"],
	"Zebstrika": ["Sap Sipper"],
	"Roggenrola": ["Sand Force"],
	"Boldore": ["Sand Force"],
	"Gigalith": ["Sand Force"],
	"Woobat": ["Simple"],
	"Swoobat": ["Simple"],
	"Drilbur": ["Mold Breaker"],
	"Excadrill": ["Mold Breaker"],
	"Audino": ["Klutz"],
	"Timburr": ["Iron Fist"],
	"Gurdurr": ["Iron Fist"],
	"Conkeldurr": ["Iron Fist"],
	"Tympole": ["Water Absorb"],
	"Palpitoad": ["Water Absorb"],
	"Seismitoad": ["Water Absorb"],
	"Throh": ["Mold Breaker"],
	"Sawk": ["Mold Breaker"],
	"Sewaddle": ["Overcoat"],
	"Swadloon": ["Overcoat"],
	"Leavanny": ["Overcoat"],
	"Venipede": ["Speed Boost"],
	"Whirlipede": ["Speed Boost"],
	"Scolipede": ["Speed Boost"],
	"Cottonee": ["Chlorophyll"],
	"Whimsicott": ["Chlorophyll"],
	"Petilil": ["Leaf Guard"],
	"Lilligant": ["Leaf Guard"],
	"Basculin": ["Mold Breaker"],
	"Basculegion": ["Mold Breaker"],
	"Sandile": ["Anger Point"],
	"Krokorok": ["Anger Point"],
	"Krookodile": ["Anger Point"],
	"Darumaka": ["Inner Focus"],
	"Darmanitan": ["Zen Mode"],
	"Maractus": ["Storm Drain"],
	"Dwebble": ["Weak Armor"],
	"Crustle": ["Weak Armor"],
	"Scraggy": ["Intimidate"],
	"Scrafty": ["Intimidate"],
	"Sigilyph": ["Tinted Lens"],
	"Tirtouga": ["Swift Swim"],
	"Carracosta": ["Swift Swim"],
	"Trubbish": ["Aftermath"],
	"Garbodor": ["Aftermath"],
	"Minccino": ["Skill Link"],
	"Cinccino": ["Skill Link"],
	"Gothita": ["Shadow Tag"],
	"Gothorita": ["Shadow Tag"],
	"Gothitelle": ["Shadow Tag"],
	"Solosis": ["Regenerator"],
	"Duosion": ["Regenerator"],
	"Reuniclus": ["Regenerator"],
	"Ducklett": ["Hydration"],
	"Swanna": ["Hydration"],
	"Vanillite": ["Weak Armor"],
	"Vanillish": ["Weak Armor"],
	"Vanilluxe": ["Weak Armor"],
	"Deerling": ["Serene Grace"],
	"Sawsbuck": ["Serene Grace"],
	"Emolga": ["Motor Drive"],
	"Karrablast": ["No Guard"],
	"Escavalier": ["Overcoat"],
	"Foongus": ["Regenerator"],
	"Amoonguss": ["Regenerator"],
	"Frillish": ["Damp"],
	"Jellicent": ["Damp"],
	"Alomomola": ["Regenerator"],
	"Joltik": ["Swarm"],
	"Galvantula": ["Swarm"],
	"Ferrothorn": ["Anticipation"],
	"Klink": ["Clear Body"],
	"Klang": ["Clear Body"],
	"Klinklang": ["Clear Body"],
	"Elgyem": ["Analytic"],
	"Beheeyem": ["Analytic"],
	"Litwick": ["Infiltrator"],
	"Lampent": ["Infiltrator"],
	"Chandelure": ["Infiltrator"],
	"Axew": ["Unnerve"],
	"Fraxure": ["Unnerve"],
	"Haxorus": ["Unnerve"],
	"Cubchoo": ["Rattled"],
	"Beartic": ["Swift Swim"],
	"Shelmet": ["Overcoat"],
	"Accelgor": ["Unburden"],
	"Stunfisk": ["Sand Veil"],
	"Mienfoo": ["Reckless"],
	"Mienshao": ["Reckless"],
	"Druddigon": ["Mold Breaker"],
	"Golett": ["No Guard"],
	"Golurk": ["No Guard"],
	"Pawniard": ["Pressure"],
	"Bisharp": ["Pressure"],
	"Kingambit": ["Pressure"],
	"Bouffalant": ["Soundproof"],
	"Rufflet": ["Hustle"],
	"Braviary": ["Defiant", "Tinted Lens"],
	"Vullaby": ["Weak Armor"],
	"Mandibuzz": ["Weak Armor"],
	"Heatmor": ["White Smoke"],
	"Durant": ["Truant"],
	"Larvesta": ["Swarm"],
	"Volcarona": ["Swarm"],
	"Tornadus": ["Defiant"],
	"Thundurus": ["Defiant"],
	"Landorus": ["Sheer Force"],
	"Chespin": ["Bulletproof"],
	"Quilladin": ["Bulletproof"],
	"Chesnaught": ["Bulletproof"],
	"Fennekin": ["Magician"],
	"Braixen": ["Magician"],
	"Delphox": ["Magician"],
	"Froakie": ["Protean"],
	"Frogadier": ["Protean"],
	"Greninja": ["Protean"],
	"Bunnelby": ["Huge Power"],
	"Diggersby": ["Huge Power"],
	"Fletchling": ["Gale Wings"],
	"Fletchinder": ["Gale Wings"],
	"Talonflame": ["Gale Wings"],
	"Scatterbug": ["Friend Guard"],
	"Spewpa": ["Friend Guard"],
	"Vivillon": ["Friend Guard"],
	"Litleo": ["Moxie"],
	"Pyroar": ["Moxie"],
	"Flabébé": ["Symbiosis"],
	"Floette": ["Symbiosis"],
	"Florges": ["Symbiosis"],
	"Skiddo": ["Grass Pelt"],
	"Gogoat": ["Grass Pelt"],
	"Pancham": ["Scrappy"],
	"Pangoro": ["Scrappy"],
	"Espurr": ["Own Tempo"],
	"Meowstic": ["Prankster", "Competitive"],
	"Spritzee": ["Aroma Veil"],
	"Aromatisse": ["Aroma Veil"],
	"Swirlix": ["Unburden"],
	"Slurpuff": ["Unburden"],
	"Inkay": ["Infiltrator"],
	"Malamar": ["Infiltrator"],
	"Binacle": ["Pickpocket"],
	"Barbaracle": ["Pickpocket"],
	"Skrelp": ["Adaptability"],
	"Dragalge": ["Adaptability"],
	"Helioptile": ["Solar Power"],
	"Heliolisk": ["Solar Power"],
	"Tyrunt": ["Sturdy"],
	"Tyrantrum": ["Rock Head"],
	"Amaura": ["Snow Warning"],
	"Aurorus": ["Snow Warning"],
	"Hawlucha": ["Mold Breaker"],
	"Dedenne": ["Plus"],
	"Carbink": ["Sturdy"],
	"Goomy": ["Gooey"],
	"Sliggoo": ["Gooey"],
	"Goodra": ["Gooey"],
	"Klefki": ["Magician"],
	"Phantump": ["Harvest"],
	"Trevenant": ["Harvest"],
	"Pumpkaboo": ["Insomnia"],
	"Gourgeist": ["Insomnia"],
	"Bergmite": ["Sturdy"],
	"Avalugg": ["Sturdy"],
	"Noibat": ["Telepathy"],
	"Noivern": ["Telepathy"],
	"Rowlet": ["Long Reach"],
	"Dartrix": ["Long Reach"],
	"Decidueye": ["Long Reach", "Scrappy"],
	"Litten": ["Intimidate"],
	"Torracat": ["Intimidate"],
	"Incineroar": ["Intimidate"],
	"Popplio": ["Liquid Voice"],
	"Brionne": ["Liquid Voice"],
	"Primarina": ["Liquid Voice"],
	"Pikipek": ["Pickup"],
	"Trumbeak": ["Pickup"],
	"Toucannon": ["Sheer Force"],
	"Yungoos": ["Adaptability"],
	"Gumshoos": ["Adaptability"],
	"Crabrawler": ["Anger Point"],
	"Crabominable": ["Anger Point"],
	"Cutiefly": ["Sweet Veil"],
	"Ribombee": ["Sweet Veil"],
	"Rockruff": ["Steadfast"],
	"Lycanroc": ["Steadfast", "No Guard"],
	"Mareanie": ["Regenerator"],
	"Toxapex": ["Regenerator"],
	"Mudbray": ["Inner Focus"],
	"Mudsdale": ["Inner Focus"],
	"Dewpider": ["Water Absorb"],
	"Araquanid": ["Water Absorb"],
	"Fomantis": ["Contrary"],
	"Lurantis": ["Contrary"],
	"Morelull": ["Rain Dish"],
	"Shiinotic": ["Rain Dish"],
	"Salandit": ["Oblivious"],
	"Salazzle": ["Oblivious"],
	"Stufful": ["Cute Charm"],
	"Bewear": ["Unnerve"],
	"Bounsweet": ["Sweet Veil"],
	"Steenee": ["Sweet Veil"],
	"Tsareena": ["Sweet Veil"],
	"Comfey": ["Natural Cure"],
	"Oranguru": ["Symbiosis"],
	"Passimian": ["Defiant"],
	"Sandygast": ["Sand Veil"],
	"Palossand": ["Sand Veil"],
	"Pyukumuku": ["Unaware"],
	"Bruxish": ["Wonder Skin"],
	"Drampa": ["Cloud Nine"],
	"Jangmo-o": ["Overcoat"],
	"Hakamo-o": ["Overcoat"],
	"Kommo-o": ["Overcoat"],
	"Tapu Koko": ["Telepathy"],
	"Tapu Lele": ["Telepathy"],
	"Tapu Bulu": ["Telepathy"],
	"Tapu Fini": ["Telepathy"],
	"Grookey": ["Grassy Surge"],
	"Thwackey": ["Grassy Surge"],
	"Rillaboom": ["Grassy Surge"],
	"Scorbunny": ["Libero"],
	"Raboot": ["Libero"],
	"Cinderace": ["Libero"],
	"Sobble": ["Sniper"],
	"Drizzile": ["Sniper"],
	"Inteleon": ["Sniper"],
	"Skwovet": ["Gluttony"],
	"Greedent": ["Gluttony"],
	"Rookidee": ["Big Pecks"],
	"Corvisquire": ["Big Pecks"],
	"Corviknight": ["Mirror Armor"],
	"Blipbug": ["Telepathy"],
	"Dottler": ["Telepathy"],
	"Orbeetle": ["Telepathy"],
	"Nickit": ["Stakeout"],
	"Thievul": ["Stakeout"],
	"Gossifleur": ["Effect Spore"],
	"Eldegoss": ["Effect Spore"],
	"Wooloo": ["Bulletproof"],
	"Dubwool": ["Bulletproof"],
	"Chewtle": ["Swift Swim"],
	"Drednaw": ["Swift Swim"],
	"Yamper": ["Rattled"],
	"Boltund": ["Competitive"],
	"Rolycoly": ["Flash Fire"],
	"Carkol": ["Flash Fire"],
	"Coalossal": ["Flash Fire"],
	"Applin": ["Bulletproof"],
	"Flapple": ["Hustle"],
	"Appletun": ["Thick Fat"],
	"Dipplin": ["Sticky Hold"],
	"Silicobra": ["Sand Veil"],
	"Sandaconda": ["Sand Veil"],
	"Arrokuda": ["Propeller Tail"],
	"Barraskewda": ["Propeller Tail"],
	"Toxel": ["Klutz"],
	"Toxtricity": ["Technician"],
	"Sizzlipede": ["Flame Body"],
	"Centiskorch": ["Flame Body"],
	"Clobbopus": ["Technician"],
	"Grapploct": ["Technician"],
	"Sinistea": ["Cursed Body"],
	"Polteageist": ["Cursed Body"],
	"Hatenna": ["Magic Bounce"],
	"Hattrem": ["Magic Bounce"],
	"Hatterene": ["Magic Bounce"],
	"Impidimp": ["Pickpocket"],
	"Morgrem": ["Pickpocket"],
	"Grimmsnarl": ["Pickpocket"],
	"Milcery": ["Aroma Veil"],
	"Alcremie": ["Aroma Veil"],
	"Falinks": ["Defiant"],
	"Pincurchin": ["Electric Surge"],
	"Snom": ["Ice Scales"],
	"Frosmoth": ["Ice Scales"],
	"Indeedee": ["Psychic Surge"],
	"Cufant": ["Heavy Metal"],
	"Copperajah": ["Heavy Metal"],
	"Dracozolt": ["Sand Rush"],
	"Arctozolt": ["Slush Rush"],
	"Dracovish": ["Sand Rush"],
	"Arctovish": ["Slush Rush"],
	"Duraludon": ["Stalwart"],
	"Dreepy": ["Cursed Body"],
	"Drakloak": ["Cursed Body"],
	"Dragapult": ["Cursed Body"],
	"Enamorus": ["Contrary"],
	"Sprigatito": ["Protean"],
	"Floragato": ["Protean"],
	"Meowscarada": ["Protean"],
	"Fuecoco": ["Unaware"],
	"Crocalor": ["Unaware"],
	"Skeledirge": ["Unaware"],
	"Quaxly": ["Moxie"],
	"Quaxwell": ["Moxie"],
	"Quaquaval": ["Moxie"],
	"Lechonk": ["Thick Fat"],
	"Oinkologne": ["Thick Fat"],
	"Tarountula": ["Stakeout"],
	"Spidops": ["Stakeout"],
	"Nymble": ["Tinted Lens"],
	"Lokix": ["Tinted Lens"],
	"Pawmi": ["Iron Fist"],
	"Pawmo": ["Iron Fist"],
	"Pawmot": ["Iron Fist"],
	"Tandemaus": ["Own Tempo"],
	"Maushold": ["Technician"],
	"Fidough": ["Klutz"],
	"Dachsbun": ["Aroma Veil"],
	"Smoliv": ["Harvest"],
	"Dolliv": ["Harvest"],
	"Arboliva": ["Harvest"],
	"Squawkabilly": ["Guts", "Sheer Force"],
	"Nacli": ["Clear Body"],
	"Naclstack": ["Clear Body"],
	"Garganacl": ["Clear Body"],
	"Charcadet": ["Flame Body"],
	"Armarouge": ["Weak Armor"],
	"Ceruledge": ["Weak Armor"],
	"Tadbulb": ["Damp"],
	"Bellibolt": ["Damp"],
	"Wattrel": ["Competitive"],
	"Kilowattrel": ["Competitive"],
	"Maschiff": ["Stakeout"],
	"Mabosstiff": ["Stakeout"],
	"Shroodle": ["Prankster"],
	"Grafaiai": ["Prankster"],
	"Bramblin": ["Infiltrator"],
	"Brambleghast": ["Infiltrator"],
	"Klawf": ["Regenerator"],
	"Capsakid": ["Klutz"],
	"Scovillain": ["Moody"],
	"Rellor": ["Shed Skin"],
	"Rabsca": ["Telepathy"],
	"Flittle": ["Speed Boost"],
	"Espathra": ["Speed Boost"],
	"Tinkatink": ["Pickpocket"],
	"Tinkatuff": ["Pickpocket"],
	"Tinkaton": ["Pickpocket"],
	"Wiglett": ["Sand Veil"],
	"Wugtrio": ["Sand Veil"],
	"Bombirdier": ["Rocky Payload"],
	"Varoom": ["Slow Start"],
	"Revavroom": ["Filter"],
	"Cyclizar": ["Regenerator"],
	"Orthworm": ["Sand Veil"],
	"Glimmet": ["Corrosion"],
	"Glimmora": ["Corrosion"],
	"Greavard": ["Fluffy"],
	"Houndstone": ["Fluffy"],
	"Flamigo": ["Costar"],
	"Cetoddle": ["Sheer Force"],
	"Cetitan": ["Sheer Force"],
	"Veluza": ["Sharpness"],
	"Dondozo": ["Water Veil"],
	"Tatsugiri": ["Storm Drain"],
	"Frigibax": ["Ice Body"],
	"Arctibax": ["Ice Body"],
	"Baxcalibur": ["Ice Body"],
	"Poltchageist": ["Heatproof"],
	"Sinistcha": ["Heatproof"],
	"Okidogi": ["Guard Dog"],
	"Munkidori": ["Frisk"],
	"Fezandipiti": ["Technician"],
}