ITEM_DICT = {
	"None": "Aucun objet",
	"Master Ball": "Master Ball",
	"Ultra Ball": "Hyper Ball",
	"Great Ball": "Super Ball",
	"Poké Ball": "Poké Ball",
	"Safari Ball": "Safari Ball",
	"Net Ball": "Filet Ball",
	"Dive Ball": "Scuba Ball",
	"Nest Ball": "Faiblo Ball",
	"Repeat Ball": "Bis Ball",
	"Timer Ball": "Chrono Ball",
	"Luxury Ball": "Luxe Ball",
	"Premier Ball": "Honor Ball",
	"Dusk Ball": "Sombre Ball",
	"Heal Ball": "Soin Ball",
	"Quick Ball": "Rapide Ball",
	"Cherish Ball": "Mémoire Ball",
	"Potion": "Potion",
	"Antidote": "Antidote",
	"Burn Heal": "Anti-Brûle",
	"Ice Heal": "Antigel",
	"Awakening": "Réveil",
	"Paralyze Heal": "Anti-Para",
	"Full Restore": "Guérison",
	"Max Potion": "Potion Max",
	"Hyper Potion": "Hyper Potion",
	"Super Potion": "Super Potion",
	"Full Heal": "Total Soin",
	"Revive": "Rappel",
	"Max Revive": "Rappel Max",
	"Fresh Water": "Eau Fraîche",
	"Soda Pop": "Soda Cool",
	"Lemonade": "Limonade",
	"Moomoo Milk": "Lait Meumeu",
	"Energy Powder": "Poudrénergie",
	"Energy Root": "Racinénergie",
	"Heal Powder": "Poudre Soin",
	"Revival Herb": "Herbe Rappel",
	"Ether": "Huile",
	"Max Ether": "Huile Max",
	"Elixir": "Élixir",
	"Max Elixir": "Élixir Max",
	"Lava Cookie": "Lava Cookie",
	"Berry Juice": "Jus de Baie",
	"Sacred Ash": "Cendre Sacrée",
	"HP Up": "PV Plus",
	"Protein": "Protéine",
	"Iron": "Fer",
	"Carbos": "Carbone",
	"Calcium": "Calcium",
	"Rare Candy": "Super Bonbon",
	"PP Up": "PP Plus",
	"Zinc": "Zinc",
	"PP Max": "PP Max",
	"Old Gateau": "Vieux Gâteau",
	"Guard Spec.": "Garde-Stats",
	"Dire Hit": "Muscle +",
	"X Attack": "Attaque +",
	"X Defense": "Défense +",
	"X Speed": "Vitesse +",
	"X Accuracy": "Précision +",
	"X Sp. Atk": "Atq. Spé. +",
	"X Sp. Def": "Déf. Spé. +",
	"Poké Doll": "Poké Poupée",
	"Fluffy Tail": "Queue Skitty",
	"Blue Flute": "Flûte Bleue",
	"Yellow Flute": "Flûte Jaune",
	"Red Flute": "Flûte Rouge",
	"Black Flute": "Flûte Noire",
	"White Flute": "Flûte Blanche",
	"Shoal Salt": "Sel Tréfonds",
	"Shoal Shell": "CoquilleTréfonds",
	"Red Shard": "Tesson Rouge",
	"Blue Shard": "Tesson Bleu",
	"Yellow Shard": "Tesson Jaune",
	"Green Shard": "Tesson Vert",
	"Super Repel": "Super Repousse",
	"Max Repel": "Repousse Max",
	"Escape Rope": "Corde Sortie",
	"Repel": "Repousse",
	"Sun Stone": "Pierre Soleil",
	"Moon Stone": "Pierre Lune",
	"Fire Stone": "Pierre Feu",
	"Thunder Stone": "Pierre Foudre",
	"Water Stone": "Pierre Eau",
	"Leaf Stone": "Pierre Plante",
	"Tiny Mushroom": "Petit Champi",
	"Big Mushroom": "Gros Champi",
	"Pearl": "Perle",
	"Big Pearl": "Grande Perle",
	"Stardust": "Poussière Étoile",
	"Star Piece": "Morceau d'Étoile",
	"Nugget": "Pépite",
	"Heart Scale": "Écaille Cœur",
	"Honey": "Miel",
	"Growth Mulch": "Fertipousse",
	"Damp Mulch": "Fertihumide",
	"Stable Mulch": "Fertistable",
	"Gooey Mulch": "Fertiglu",
	"Root Fossil": "Fossile Racine",
	"Claw Fossil": "Fossile Griffe",
	"Helix Fossil": "Nautile",
	"Dome Fossil": "Fossile Dôme",
	"Old Amber": "Vieil Ambre",
	"Armor Fossil": "Fossile Armure",
	"Skull Fossil": "Fossile Crâne",
	"Rare Bone": "Os Rare",
	"Shiny Stone": "Pierre Éclat",
	"Dusk Stone": "Pierre Nuit",
	"Dawn Stone": "Pierre Aube",
	"Oval Stone": "Pierre Ovale",
	"Odd Keystone": "Clé de Voûte",
	"Griseous Orb": "Orbe Platiné",
	"Tea": "Thé",
	"???": "???",
	"Autograph": "Dédicace de Bob",
	"Douse Drive": "Module Aqua",
	"Shock Drive": "Module Choc",
	"Burn Drive": "Module Pyro",
	"Chill Drive": "Module Cryo",
	"???": "???",
	"Pokémon Box Link": "Boîte Pokémon",
	"Medicine Pocket": "Trousse de Soins",
	"TM Case": "Boîte CT",
	"Candy Jar": "Bonbonnière",
	"Power-Up Pocket": "Poche à Renforts",
	"Clothing Trunk": "Malle à Costumes",
	"Catching Pocket": "Poche de Capture",
	"Battle Pocket": "Poche de Combat",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"Sweet Heart": "Chococœur",
	"Adamant Orb": "Orbe Adamant",
	"Lustrous Orb": "Orbe Perlé",
	"Greet Mail": "Lettre Salut",
	"Favored Mail": "Lettre Fan",
	"RSVP Mail": "Lettre Invit",
	"Thanks Mail": "Lettre Merci",
	"Inquiry Mail": "Lettre Demande",
	"Like Mail": "Lettre Avis",
	"Reply Mail": "Lettre Réponse",
	"Bridge Mail S": "Lettre Pont S",
	"Bridge Mail D": "Lettre Pont Y",
	"Bridge Mail T": "Lettre Pont F",
	"Bridge Mail V": "Lettre Pont H",
	"Bridge Mail M": "Lettre Pont I",
	"Cheri Berry": "Baie Ceriz",
	"Chesto Berry": "Baie Maron",
	"Pecha Berry": "Baie Pêcha",
	"Rawst Berry": "Baie Fraive",
	"Aspear Berry": "Baie Willia",
	"Leppa Berry": "Baie Mepo",
	"Oran Berry": "Baie Oran",
	"Persim Berry": "Baie Kika",
	"Lum Berry": "Baie Prine",
	"Sitrus Berry": "Baie Sitrus",
	"Figy Berry": "Baie Figuy",
	"Wiki Berry": "Baie Wiki",
	"Mago Berry": "Baie Mago",
	"Aguav Berry": "Baie Gowav",
	"Iapapa Berry": "Baie Papaya",
	"Razz Berry": "Baie Framby",
	"Bluk Berry": "Baie Remu",
	"Nanab Berry": "Baie Nanab",
	"Wepear Berry": "Baie Repoi",
	"Pinap Berry": "Baie Nanana",
	"Pomeg Berry": "Baie Grena",
	"Kelpsy Berry": "Baie Alga",
	"Qualot Berry": "Baie Qualot",
	"Hondew Berry": "Baie Lonme",
	"Grepa Berry": "Baie Résin",
	"Tamato Berry": "Baie Tamato",
	"Cornn Berry": "Baie Siam",
	"Magost Berry": "Baie Mangou",
	"Rabuta Berry": "Baie Rabuta",
	"Nomel Berry": "Baie Tronci",
	"Spelon Berry": "Baie Kiwan",
	"Pamtre Berry": "Baie Palma",
	"Watmel Berry": "Baie Stekpa",
	"Durin Berry": "Baie Durin",
	"Belue Berry": "Baie Myrte",
	"Occa Berry": "Baie Chocco",
	"Passho Berry": "Baie Pocpoc",
	"Wacan Berry": "Baie Parma",
	"Rindo Berry": "Baie Ratam",
	"Yache Berry": "Baie Nanone",
	"Chople Berry": "Baie Pomroz",
	"Kebia Berry": "Baie Kébia",
	"Shuca Berry": "Baie Jouca",
	"Coba Berry": "Baie Cobaba",
	"Payapa Berry": "Baie Yapap",
	"Tanga Berry": "Baie Panga",
	"Charti Berry": "Baie Charti",
	"Kasib Berry": "Baie Sédra",
	"Haban Berry": "Baie Fraigo",
	"Colbur Berry": "Baie Lampou",
	"Babiri Berry": "Baie Babiri",
	"Chilan Berry": "Baie Zalis",
	"Liechi Berry": "Baie Lichii",
	"Ganlon Berry": "Baie Lingan",
	"Salac Berry": "Baie Sailak",
	"Petaya Berry": "Baie Pitaye",
	"Apicot Berry": "Baie Abriko",
	"Lansat Berry": "Baie Lansat",
	"Starf Berry": "Baie Frista",
	"Enigma Berry": "Baie Enigma",
	"Micle Berry": "Baie Micle",
	"Custap Berry": "Baie Chérim",
	"Jaboca Berry": "Baie Jaboca",
	"Rowap Berry": "Baie Pommo",
	"Bright Powder": "Poudre Claire",
	"White Herb": "Herbe Blanche",
	"Macho Brace": "Bracelet Macho",
	"Exp. Share": "Multi Exp",
	"Quick Claw": "Vive Griffe",
	"Soothe Bell": "Grelot Zen",
	"Mental Herb": "Herbe Mental",
	"Choice Band": "Bandeau Choix",
	"King's Rock": "Roche Royale",
	"Silver Powder": "Poudre Argentée",
	"Amulet Coin": "Pièce Rune",
	"Cleanse Tag": "Rune Purifiante",
	"Soul Dew": "Rosée Âme",
	"Deep Sea Tooth": "Dent Océan",
	"Deep Sea Scale": "Écaille Océan",
	"Smoke Ball": "Boule Fumée",
	"Everstone": "Pierre Stase",
	"Focus Band": "Bandeau",
	"Lucky Egg": "Œuf Chance",
	"Scope Lens": "Lentilscope",
	"Metal Coat": "Peau Métal",
	"Leftovers": "Restes",
	"Dragon Scale": "Écaille Draco",
	"Light Ball": "Balle Lumière",
	"Soft Sand": "Sable Doux",
	"Hard Stone": "Pierre Dure",
	"Miracle Seed": "Graine Miracle",
	"Black Glasses": "Lunettes Noires",
	"Black Belt": "Ceinture Noire",
	"Magnet": "Aimant",
	"Mystic Water": "Eau Mystique",
	"Sharp Beak": "Bec Pointu",
	"Poison Barb": "Pic Venin",
	"Never-Melt Ice": "Glace Éternelle",
	"Spell Tag": "Rune Sort",
	"Twisted Spoon": "Cuillère Tordue",
	"Charcoal": "Charbon",
	"Dragon Fang": "Croc Dragon",
	"Silk Scarf": "Mouchoir Soie",
	"Upgrade": "Améliorator",
	"Shell Bell": "Grelot Coque",
	"Sea Incense": "Encens Mer",
	"Lax Incense": "Encens Doux",
	"Lucky Punch": "Poing Chance",
	"Metal Powder": "Poudre Métal",
	"Thick Club": "Masse Os",
	"Leek": "Poireau",
	"Red Scarf": "Foulard Rouge",
	"Blue Scarf": "Foulard Bleu",
	"Pink Scarf": "Foulard Rose",
	"Green Scarf": "Foulard Vert",
	"Yellow Scarf": "Foulard Jaune",
	"Wide Lens": "Loupe",
	"Muscle Band": "Bandeau Muscle",
	"Wise Glasses": "Lunettes Sages",
	"Expert Belt": "Ceinture Pro",
	"Light Clay": "Lumargile",
	"Life Orb": "Orbe Vie",
	"Power Herb": "Herbe Pouvoir",
	"Toxic Orb": "Orbe Toxique",
	"Flame Orb": "Orbe Flamme",
	"Quick Powder": "Poudre Vite",
	"Focus Sash": "Ceinture Force",
	"Zoom Lens": "Lentille Zoom",
	"Metronome": "Métronome",
	"Iron Ball": "Balle Fer",
	"Lagging Tail": "Ralentiqueue",
	"Destiny Knot": "Nœud Destin",
	"Black Sludge": "Boue Noire",
	"Icy Rock": "Roche Glace",
	"Smooth Rock": "Roche Lisse",
	"Heat Rock": "Roche Chaude",
	"Damp Rock": "Roche Humide",
	"Grip Claw": "Accro Griffe",
	"Choice Scarf": "Mouchoir Choix",
	"Sticky Barb": "Piquants",
	"Power Bracer": "Poignet Pouvoir",
	"Power Belt": "Ceinture Pouvoir",
	"Power Lens": "Lentille Pouvoir",
	"Power Band": "Bandeau Pouvoir",
	"Power Anklet": "Chaîne Pouvoir",
	"Power Weight": "Poids Pouvoir",
	"Shed Shell": "Carapace Mue",
	"Big Root": "Grosse Racine",
	"Choice Specs": "Lunettes Choix",
	"Flame Plate": "Plaque Flamme",
	"Splash Plate": "Plaque Hydro",
	"Zap Plate": "Plaque Volt",
	"Meadow Plate": "Plaque Herbe",
	"Icicle Plate": "Plaque Glace",
	"Fist Plate": "Plaque Poing",
	"Toxic Plate": "Plaque Toxicité",
	"Earth Plate": "Plaque Terre",
	"Sky Plate": "Plaque Ciel",
	"Mind Plate": "Plaque Esprit",
	"Insect Plate": "Plaque Insecte",
	"Stone Plate": "Plaque Roc",
	"Spooky Plate": "Plaque Fantôme",
	"Draco Plate": "Plaque Draco",
	"Dread Plate": "Plaque Ombre",
	"Iron Plate": "Plaque Fer",
	"Odd Incense": "Encens Bizarre",
	"Rock Incense": "Encens Roc",
	"Full Incense": "Encens Plein",
	"Wave Incense": "Encens Vague",
	"Rose Incense": "Encens Fleur",
	"Luck Incense": "Encens Veine",
	"Pure Incense": "Encens Pur",
	"Protector": "Protecteur",
	"Electirizer": "Électriseur",
	"Magmarizer": "Magmariseur",
	"Dubious Disc": "CD Douteux",
	"Reaper Cloth": "Tissu Fauche",
	"Razor Claw": "Griffe Rasoir",
	"Razor Fang": "Croc Rasoir",
	"TM001": "CT001",
	"TM002": "CT002",
	"TM003": "CT003",
	"TM004": "CT004",
	"TM005": "CT005",
	"TM006": "CT006",
	"TM007": "CT007",
	"TM008": "CT008",
	"TM009": "CT009",
	"TM010": "CT010",
	"TM011": "CT011",
	"TM012": "CT012",
	"TM013": "CT013",
	"TM014": "CT014",
	"TM015": "CT015",
	"TM016": "CT016",
	"TM017": "CT017",
	"TM018": "CT018",
	"TM019": "CT019",
	"TM020": "CT020",
	"TM021": "CT021",
	"TM022": "CT022",
	"TM023": "CT023",
	"TM024": "CT024",
	"TM025": "CT025",
	"TM026": "CT026",
	"TM027": "CT027",
	"TM028": "CT028",
	"TM029": "CT029",
	"TM030": "CT030",
	"TM031": "CT031",
	"TM032": "CT032",
	"TM033": "CT033",
	"TM034": "CT034",
	"TM035": "CT035",
	"TM036": "CT036",
	"TM037": "CT037",
	"TM038": "CT038",
	"TM039": "CT039",
	"TM040": "CT040",
	"TM041": "CT041",
	"TM042": "CT042",
	"TM043": "CT043",
	"TM044": "CT044",
	"TM045": "CT045",
	"TM046": "CT046",
	"TM047": "CT047",
	"TM048": "CT048",
	"TM049": "CT049",
	"TM050": "CT050",
	"TM051": "CT051",
	"TM052": "CT052",
	"TM053": "CT053",
	"TM054": "CT054",
	"TM055": "CT055",
	"TM056": "CT056",
	"TM057": "CT057",
	"TM058": "CT058",
	"TM059": "CT059",
	"TM060": "CT060",
	"TM061": "CT061",
	"TM062": "CT062",
	"TM063": "CT063",
	"TM064": "CT064",
	"TM065": "CT065",
	"TM066": "CT066",
	"TM067": "CT067",
	"TM068": "CT068",
	"TM069": "CT069",
	"TM070": "CT070",
	"TM071": "CT071",
	"TM072": "CT072",
	"TM073": "CT073",
	"TM074": "CT074",
	"TM075": "CT075",
	"TM076": "CT076",
	"TM077": "CT077",
	"TM078": "CT078",
	"TM079": "CT079",
	"TM080": "CT080",
	"TM081": "CT081",
	"TM082": "CT082",
	"TM083": "CT083",
	"TM084": "CT084",
	"TM085": "CT085",
	"TM086": "CT086",
	"TM087": "CT087",
	"TM088": "CT088",
	"TM089": "CT089",
	"TM090": "CT090",
	"TM091": "CT091",
	"TM092": "CT092",
	"HM01": "CS01",
	"HM02": "CS02",
	"HM03": "CS03",
	"HM04": "CS04",
	"HM05": "CS05",
	"HM06": "CS06",
	"???": "???",
	"???": "???",
	"Explorer Kit": "Explorakit",
	"Loot Sack": "Sac Butin",
	"Rule Book": "Livre Règles",
	"Poké Radar": "Poké Radar",
	"Point Card": "Carte à Points",
	"Guidebook": "Notes d'Aventure",
	"Sticker Case": "Boîte à Sceaux",
	"Fashion Case": "Coffret Mode",
	"Sticker Bag": "Sac Sceaux",
	"Pal Pad": "Registre Ami",
	"Works Key": "Clé Parc Éolien",
	"Old Charm": "Vieux Grigri",
	"Galactic Key": "Clé Galaxie",
	"Red Chain": "Chaîne Rouge",
	"Town Map": "Carte",
	"Vs. Seeker": "Cherch'Combat",
	"Coin Case": "Boîte Jetons",
	"Old Rod": "Canne",
	"Good Rod": "Super Canne",
	"Super Rod": "Méga Canne",
	"Sprayduck": "Kwakarrosoir",
	"Poffin Case": "Boîte à Poffins",
	"Bike": "Bicyclette",
	"Suite Key": "Clé de Chambre",
	"Oak's Letter": "Lettre Chen",
	"Lunar Feather": "Plume Lune",
	"Member Card": "Carte Membre",
	"Azure Flute": "Flûte Azur",
	"S.S. Ticket": "Passe Bateau",
	"Contest Pass": "Passe Concours",
	"Magma Stone": "Pierre Magma",
	"Parcel": "Colis",
	"Coupon 1": "Bon 1",
	"Coupon 2": "Bon 2",
	"Coupon 3": "Bon 3",
	"Storage Key": "Clé du Hangar",
	"Secret Medicine": "Remède Secret",
	"Vs. Recorder": "Magnéto VS",
	"Gracidea": "Gracidée",
	"Secret Key": "Clé Secrète",
	"Apricorn Box": "Boîte Noigrume",
	"Unown Report": "Carnet Zarbi",
	"Berry Pots": "Plante-Baies",
	"Dowsing Machine": "Cherch'Objet",
	"Blue Card": "Carte Bleue",
	"Slowpoke Tail": "Queue Ramoloss",
	"Clear Bell": "Glas Transparent",
	"Card Key": "Carte Magnétique",
	"Basement Key": "Clé Sous-Sol",
	"Squirt Bottle": "Carapuce à O",
	"Red Scale": "Écaille Rouge",
	"Lost Item": "Objet perdu",
	"Pass": "Passe Train",
	"Machine Part": "Partie Machine",
	"Silver Feather": "Argent'Aile",
	"Rainbow Feather": "Arc-en-Ci'Aile",
	"Mystery Egg": "Œuf Mystère",
	"Red Apricorn": "Noigrume Rouge",
	"Blue Apricorn": "Noigrume Bleu",
	"Yellow Apricorn": "Noigrume Jaune",
	"Green Apricorn": "Noigrume Vert",
	"Pink Apricorn": "Noigrume Rose",
	"White Apricorn": "Noigrume Blanc",
	"Black Apricorn": "Noigrume Noir",
	"Fast Ball": "Speed Ball",
	"Level Ball": "Niveau Ball",
	"Lure Ball": "Appât Ball",
	"Heavy Ball": "Masse Ball",
	"Love Ball": "Love Ball",
	"Friend Ball": "Copain Ball",
	"Moon Ball": "Lune Ball",
	"Sport Ball": "Compét'Ball",
	"Park Ball": "Parc Ball",
	"Photo Album": "Album Photo",
	"GB Sounds": "Lecteur GB",
	"Tidal Bell": "Glas Tempête",
	"Rage Candy Bar": "Bonbon Rage",
	"Data Card 01": "Carte Mémo01",
	"Data Card 02": "Carte Mémo02",
	"Data Card 03": "Carte Mémo03",
	"Data Card 04": "Carte Mémo04",
	"Data Card 05": "Carte Mémo05",
	"Data Card 06": "Carte Mémo06",
	"Data Card 07": "Carte Mémo07",
	"Data Card 08": "Carte Mémo08",
	"Data Card 09": "Carte Mémo09",
	"Data Card 10": "Carte Mémo10",
	"Data Card 11": "Carte Mémo11",
	"Data Card 12": "Carte Mémo12",
	"Data Card 13": "Carte Mémo13",
	"Data Card 14": "Carte Mémo14",
	"Data Card 15": "Carte Mémo15",
	"Data Card 16": "Carte Mémo16",
	"Data Card 17": "Carte Mémo17",
	"Data Card 18": "Carte Mémo18",
	"Data Card 19": "Carte Mémo19",
	"Data Card 20": "Carte Mémo20",
	"Data Card 21": "Carte Mémo21",
	"Data Card 22": "Carte Mémo22",
	"Data Card 23": "Carte Mémo23",
	"Data Card 24": "Carte Mémo24",
	"Data Card 25": "Carte Mémo25",
	"Data Card 26": "Carte Mémo26",
	"Data Card 27": "Carte Mémo27",
	"Jade Orb": "Orbe Vert",
	"Lock Capsule": "Poké Écrin",
	"Red Orb": "Gemme Rouge",
	"Blue Orb": "Gemme Bleue",
	"Enigma Stone": "Mystécristal",
	"Prism Scale": "Bel'Écaille",
	"Eviolite": "Évoluroc",
	"Float Stone": "Pierrallégée",
	"Rocky Helmet": "Casque Brut",
	"Air Balloon": "Ballon",
	"Red Card": "Carton Rouge",
	"Ring Target": "Point de Mire",
	"Binding Band": "Bande Étreinte",
	"Absorb Bulb": "Bulbe",
	"Cell Battery": "Pile",
	"Eject Button": "Bouton Fuite",
	"Fire Gem": "Joyau Feu",
	"Water Gem": "Joyau Eau",
	"Electric Gem": "Joyau Électrik",
	"Grass Gem": "Joyau Plante",
	"Ice Gem": "Joyau Glace",
	"Fighting Gem": "Joyau Combat",
	"Poison Gem": "Joyau Poison",
	"Ground Gem": "Joyau Sol",
	"Flying Gem": "Joyau Vol",
	"Psychic Gem": "Joyau Psy",
	"Bug Gem": "Joyau Insecte",
	"Rock Gem": "Joyau Roche",
	"Ghost Gem": "Joyau Spectre",
	"Dragon Gem": "Joyau Dragon",
	"Dark Gem": "Joyau Ténèbres",
	"Steel Gem": "Joyau Acier",
	"Normal Gem": "Joyau Normal",
	"Health Feather": "Plume Santé",
	"Muscle Feather": "Plume Force",
	"Resist Feather": "Plume Armure",
	"Genius Feather": "Plume Esprit",
	"Clever Feather": "Plume Mental",
	"Swift Feather": "Plume Sprint",
	"Pretty Feather": "Jolie Plume",
	"Cover Fossil": "Fossile Plaque",
	"Plume Fossil": "Fossile Plume",
	"Liberty Pass": "Passe Liberté",
	"Pass Orb": "Offrisphère",
	"Dream Ball": "Rêve Ball",
	"Poké Toy": "Poké Plumet",
	"Prop Case": "Boîte Parure",
	"Dragon Skull": "Crâne Dragon",
	"Balm Mushroom": "Champi Suave",
	"Big Nugget": "Maxi Pépite",
	"Pearl String": "Perle Triple",
	"Comet Shard": "Morceau Comète",
	"Relic Copper": "Vieux Sou",
	"Relic Silver": "Vieil Écu",
	"Relic Gold": "Vieux Ducat",
	"Relic Vase": "Vieux Vase",
	"Relic Band": "Vieux Bijou",
	"Relic Statue": "Vieux Santon",
	"Relic Crown": "Vieux Tortil",
	"Casteliacone": "Glace Volute",
	"Dire Hit 2": "Muscle 2",
	"X Speed 2": "Vitesse 2",
	"X Sp. Atk 2": "Atq. Spé. 2",
	"X Sp. Def 2": "Déf. Spé. 2",
	"X Defense 2": "Défense 2",
	"X Attack 2": "Attaque 2",
	"X Accuracy 2": "Précision 2",
	"X Speed 3": "Vitesse 3",
	"X Sp. Atk 3": "Atq. Spé. 3",
	"X Sp. Def 3": "Déf. Spé. 3",
	"X Defense 3": "Défense 3",
	"X Attack 3": "Attaque 3",
	"X Accuracy 3": "Précision 3",
	"X Speed 6": "Vitesse 6",
	"X Sp. Atk 6": "Atq. Spé. 6",
	"X Sp. Def 6": "Déf. Spé. 6",
	"X Defense 6": "Défense 6",
	"X Attack 6": "Attaque 6",
	"X Accuracy 6": "Précision 6",
	"Ability Urge": "Appel Talent",
	"Item Drop": "Jette Objet",
	"Item Urge": "Appel Objet",
	"Reset Urge": "Réamorçage",
	"Dire Hit 3": "Muscle 3",
	"Light Stone": "Galet Blanc",
	"Dark Stone": "Galet Noir",
	"TM093": "CT093",
	"TM094": "CT094",
	"TM095": "CT095",
	"Xtransceiver": "Vokit",
	"???": "???",
	"Gram 1": "Courrier 1",
	"Gram 2": "Courrier 2",
	"Gram 3": "Courrier 3",
	"Xtransceiver": "Vokit",
	"Medal Box": "Boîte Médailles",
	"DNA Splicers": "Pointeau ADN",
	"DNA Splicers": "Pointeau ADN",
	"Permit": "Permis",
	"Oval Charm": "Charme Ovale",
	"Shiny Charm": "Charme Chroma",
	"Plasma Card": "Carte Plasma",
	"Grubby Hanky": "Mouchoir Sale",
	"Colress Machine": "Nikodule",
	"Dropped Item": "Objet Trouvé",
	"Dropped Item": "Objet Trouvé",
	"Reveal Glass": "Miroir Sacré",
	"Weakness Policy": "Vulné-Assurance",
	"Assault Vest": "Veste de Combat",
	"Holo Caster": "Holokit",
	"Prof's Letter": "Lettre du Prof",
	"Roller Skates": "Rollers",
	"Pixie Plate": "Plaque Pixie",
	"Ability Capsule": "Pilule Talent",
	"Whipped Dream": "Chantibonbon",
	"Sachet": "Sachet Senteur",
	"Luminous Moss": "Lichen Lumineux",
	"Snowball": "Boule de Neige",
	"Safety Goggles": "Lunettes Filtre",
	"Poké Flute": "Poké Flûte",
	"Rich Mulch": "Fertibondance",
	"Surprise Mulch": "Fertistantané",
	"Boost Mulch": "Fertibérance",
	"Amaze Mulch": "Fertiprodige",
	"Gengarite": "Ectoplasmite",
	"Gardevoirite": "Gardevoirite",
	"Ampharosite": "Pharampite",
	"Venusaurite": "Florizarrite",
	"Charizardite X": "Dracaufite X",
	"Blastoisinite": "Tortankite",
	"Mewtwonite X": "Mewtwoïte X",
	"Mewtwonite Y": "Mewtwoïte Y",
	"Blazikenite": "Braségalite",
	"Medichamite": "Charminite",
	"Houndoominite": "Démolossite",
	"Aggronite": "Galekingite",
	"Banettite": "Branettite",
	"Tyranitarite": "Tyranocivite",
	"Scizorite": "Cizayoxite",
	"Pinsirite": "Scarabruite",
	"Aerodactylite": "Ptéraïte",
	"Lucarionite": "Lucarite",
	"Abomasite": "Blizzarite",
	"Kangaskhanite": "Kangourexite",
	"Gyaradosite": "Léviatorite",
	"Absolite": "Absolite",
	"Charizardite Y": "Dracaufite Y",
	"Alakazite": "Alakazamite",
	"Heracronite": "Scarhinoïte",
	"Mawilite": "Mysdibulite",
	"Manectite": "Élecsprintite",
	"Garchompite": "Carchacrokite",
	"Latiasite": "Latiasite",
	"Latiosite": "Latiosite",
	"Roseli Berry": "Baie Selro",
	"Kee Berry": "Baie Éka",
	"Maranga Berry": "Baie Rangma",
	"Sprinklotad": "Nénurrosoir",
	"TM096": "CT096",
	"TM097": "CT097",
	"TM098": "CT098",
	"TM099": "CT099",
	"TM100": "CT100",
	"Power Plant Pass": "Passe Centrale",
	"Mega Ring": "Méga-Anneau",
	"Intriguing Stone": "Pierre Insolite",
	"Common Stone": "Pierre Ordinaire",
	"Discount Coupon": "Bon Réduction",
	"Elevator Key": "Clé Ascenseur",
	"TMV Pass": "Passe TMV",
	"Honor of Kalos": "Insigne de Kalos",
	"Adventure Guide": "ABC Aventure",
	"Strange Souvenir": "Bibelot Bizarre",
	"Lens Case": "Boîte Lentilles",
	"Makeup Bag": "Trousse Beauté",
	"Travel Trunk": "Malle Penderie",
	"Lumiose Galette": "Galette Illumis",
	"Shalour Sable": "Sablé Yantreizh",
	"Jaw Fossil": "Fossile Mâchoire",
	"Sail Fossil": "Fossile Nageoire",
	"Looker Ticket": "Ticket Beladonis",
	"Bike": "Bicyclette",
	"Holo Caster": "Holokit",
	"Fairy Gem": "Joyau Fée",
	"Mega Charm": "Méga-Charme",
	"Mega Glove": "Méga-Gant",
	"Mach Bike": "Vélo de Course",
	"Acro Bike": "Vélo Cross",
	"Wailmer Pail": "Wailmerrosoir",
	"Devon Parts": "Pack Devon",
	"Soot Sack": "Sac à Suie",
	"Basement Key": "Clé Sous-Sol",
	"Pokéblock Kit": "Kit Pokébloc",
	"Letter": "Lettre à Pierre",
	"Eon Ticket": "Passe Éon",
	"Scanner": "Scanner",
	"Go-Goggles": "Lunettes Sable",
	"Meteorite": "Météorite",
	"Key to Room 1": "Clé Salle 1",
	"Key to Room 2": "Clé Salle 2",
	"Key to Room 4": "Clé Salle 4",
	"Key to Room 6": "Clé Salle 6",
	"Storage Key": "Clé du Hangar",
	"Devon Scope": "Devon Scope",
	"S.S. Ticket": "Passe Bateau",
	"HM07": "CS07",
	"Devon Scuba Gear": "Plongeur Devon",
	"Contest Costume": "Costume Live",
	"Contest Costume": "Robe Live",
	"Magma Suit": "Scaph. Magma",
	"Aqua Suit": "Scaphandre Aqua",
	"Pair of Tickets": "Ticket Duo",
	"Mega Bracelet": "Méga-Bracelet",
	"Mega Pendant": "Méga-Pendentif",
	"Mega Glasses": "Méga-Lunettes",
	"Mega Anchor": "Méga-Ancre",
	"Mega Stickpin": "Méga-Pin's",
	"Mega Tiara": "Méga-Tiare",
	"Mega Anklet": "Méga-Grève",
	"Meteorite": "Météorite",
	"Swampertite": "Laggronite",
	"Sceptilite": "Jungkite",
	"Sablenite": "Ténéfixite",
	"Altarianite": "Altarite",
	"Galladite": "Gallamite",
	"Audinite": "Nanméouïte",
	"Metagrossite": "Métalossite",
	"Sharpedonite": "Sharpedite",
	"Slowbronite": "Flagadossite",
	"Steelixite": "Steelixite",
	"Pidgeotite": "Roucarnagite",
	"Glalitite": "Oniglalite",
	"Diancite": "Diancite",
	"Prison Bottle": "Vase Scellé",
	"Mega Cuff": "Méga-Manchette",
	"Cameruptite": "Caméruptite",
	"Lopunnite": "Lockpinite",
	"Salamencite": "Drattakite",
	"Beedrillite": "Dardargnite",
	"Meteorite": "Météorite",
	"Meteorite": "Météorite",
	"Key Stone": "Gemme Sésame",
	"Meteorite Shard": "Éclat Météorite",
	"Eon Flute": "Flûte Éon",
	"Normalium Z": "Normazélite",
	"Firium Z": "Pyrozélite",
	"Waterium Z": "Aquazélite",
	"Electrium Z": "Voltazélite",
	"Grassium Z": "Florazélite",
	"Icium Z": "Cryozélite",
	"Fightinium Z": "Combazélite",
	"Poisonium Z": "Toxizélite",
	"Groundium Z": "Terrazélite",
	"Flyinium Z": "Aérozélite",
	"Psychium Z": "Psychézélite",
	"Buginium Z": "Insectozélite",
	"Rockium Z": "Rocazélite",
	"Ghostium Z": "Spectrozélite",
	"Dragonium Z": "Dracozélite",
	"Darkinium Z": "Ténébrozélite",
	"Steelium Z": "Métallozélite",
	"Fairium Z": "Nymphézélite",
	"Pikanium Z": "Pikazélite",
	"Bottle Cap": "Capsule d'Argent",
	"Gold Bottle Cap": "Capsule d'Or",
	"Z-Ring": "Bracelet Z",
	"Decidium Z": "Archézélite",
	"Incinium Z": "Félinozélite",
	"Primarium Z": "Oratozélite",
	"Tapunium Z": "Tokozélite",
	"Marshadium Z": "Marshadozélite",
	"Aloraichium Z": "Aloraïzélite",
	"Snorlium Z": "Ronflézélite",
	"Eevium Z": "Évolizélite",
	"Mewnium Z": "Mewzélite",
	"Normalium Z": "Normazélite",
	"Firium Z": "Pyrozélite",
	"Waterium Z": "Aquazélite",
	"Electrium Z": "Voltazélite",
	"Grassium Z": "Florazélite",
	"Icium Z": "Cryozélite",
	"Fightinium Z": "Combazélite",
	"Poisonium Z": "Toxizélite",
	"Groundium Z": "Terrazélite",
	"Flyinium Z": "Aérozélite",
	"Psychium Z": "Psychézélite",
	"Buginium Z": "Insectozélite",
	"Rockium Z": "Rocazélite",
	"Ghostium Z": "Spectrozélite",
	"Dragonium Z": "Dracozélite",
	"Darkinium Z": "Ténébrozélite",
	"Steelium Z": "Métallozélite",
	"Fairium Z": "Nymphézélite",
	"Pikanium Z": "Pikazélite",
	"Decidium Z": "Archézélite",
	"Incinium Z": "Félinozélite",
	"Primarium Z": "Oratozélite",
	"Tapunium Z": "Tokozélite",
	"Marshadium Z": "Marshadozélite",
	"Aloraichium Z": "Aloraïzélite",
	"Snorlium Z": "Ronflézélite",
	"Eevium Z": "Évolizélite",
	"Mewnium Z": "Mewzélite",
	"Pikashunium Z": "Pikachazélite",
	"Pikashunium Z": "Pikachazélite",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"Forage Bag": "Sac Ingrédients",
	"Fishing Rod": "Canne à Pêche",
	"Professor's Mask": "Masque du Prof",
	"Festival Ticket": "Festicket",
	"Sparkling Stone": "Gemme Lumière",
	"Adrenaline Orb": "Orbe Frousse",
	"Zygarde Cube": "Boîte Zygarde",
	"???": "???",
	"Ice Stone": "Pierre Glace",
	"Ride Pager": "Appel-Monture",
	"Beast Ball": "Ultra Ball",
	"Big Malasada": "Malasada Maxi",
	"Red Nectar": "Nectar Rouge",
	"Yellow Nectar": "Nectar Jaune",
	"Pink Nectar": "Nectar Rose",
	"Purple Nectar": "Nectar Mauve",
	"Sun Flute": "Flûte du Soleil",
	"Moon Flute": "Flûte de la Lune",
	"???": "???",
	"Enigmatic Card": "Message Mystère",
	"Silver Razz Berry": "Baie Framby argentée",
	"Golden Razz Berry": "Baie Framby dorée",
	"Silver Nanab Berry": "Baie Nanab argentée",
	"Golden Nanab Berry": "Baie Nanab dorée",
	"Silver Pinap Berry": "Baie Nanana argentée",
	"Golden Pinap Berry": "Baie Nanana dorée",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"Secret Key": "Clé Secrète",
	"S.S. Ticket": "Passe Bateau",
	"Silph Scope": "Scope Sylphe",
	"Parcel": "Colis",
	"Card Key": "Carte Magnétique",
	"Gold Teeth": "Dentier en Or",
	"Lift Key": "Clé Ascenseur",
	"Terrain Extender": "Champ'Duit",
	"Protective Pads": "Pare-Effet",
	"Electric Seed": "Graine Électrik",
	"Psychic Seed": "Graine Psychique",
	"Misty Seed": "Graine Brume",
	"Grassy Seed": "Graine Herbe",
	"Stretchy Spring": "Ressort Détendu",
	"Chalky Stone": "Craie",
	"Marble": "Bille",
	"Lone Earring": "Boucle d'Oreille",
	"Beach Glass": "Galet de Verre",
	"Gold Leaf": "Feuille Dorée",
	"Silver Leaf": "Feuille Argentée",
	"Polished Mud Ball": "Boulette de Boue",
	"Tropical Shell": "Coquille du Sud",
	"Leaf Letter": "Lettre Végétale",
	"Leaf Letter": "Lettre Végétale",
	"Small Bouquet": "Petit Bouquet",
	"???": "???",
	"???": "???",
	"???": "???",
	"Lure": "Parfum",
	"Super Lure": "Super Parfum",
	"Max Lure": "Parfum Max",
	"Pewter Crunchies": "Crok'Argenta",
	"Fighting Memory": "ROM Combat",
	"Flying Memory": "ROM Vol",
	"Poison Memory": "ROM Poison",
	"Ground Memory": "ROM Sol",
	"Rock Memory": "ROM Roche",
	"Bug Memory": "ROM Insecte",
	"Ghost Memory": "ROM Spectre",
	"Steel Memory": "ROM Acier",
	"Fire Memory": "ROM Feu",
	"Water Memory": "ROM Eau",
	"Grass Memory": "ROM Plante",
	"Electric Memory": "ROM Électrik",
	"Psychic Memory": "ROM Psy",
	"Ice Memory": "ROM Glace",
	"Dragon Memory": "ROM Dragon",
	"Dark Memory": "ROM Ténèbres",
	"Fairy Memory": "ROM Fée",
	"Solganium Z": "Solgazélite",
	"Lunalium Z": "Lunazélite",
	"Ultranecrozium Z": "Ultranécrozélite",
	"Mimikium Z": "Mimiquizélite",
	"Lycanium Z": "Lougarozélite",
	"Kommonium Z": "Ékaïzélite",
	"Solganium Z": "Solgazélite",
	"Lunalium Z": "Lunazélite",
	"Ultranecrozium Z": "Ultranécrozélite",
	"Mimikium Z": "Mimiquizélite",
	"Lycanium Z": "Lougarozélite",
	"Kommonium Z": "Ékaïzélite",
	"Z-Power Ring": "Super Bracelet Z",
	"Pink Petal": "Pétale Rose",
	"Orange Petal": "Pétale Orange",
	"Blue Petal": "Pétale Bleu",
	"Red Petal": "Pétale Rouge",
	"Green Petal": "Pétale Vert",
	"Yellow Petal": "Pétale Jaune",
	"Purple Petal": "Pétale Violet",
	"Rainbow Flower": "Fleur 7 Couleurs",
	"Surge Badge": "Fulguro-Badge",
	"N-Solarizer": "Necrosol",
	"N-Lunarizer": "Necroluna",
	"N-Solarizer": "Necrosol",
	"N-Lunarizer": "Necroluna",
	"Ilima's Normalium Z": "Cristal Z Althéo",
	"Left Poké Ball": "Poké Ball donnée",
	"Roto Hatch": "Moti-Couveuse",
	"Roto Bargain": "Moti-Promo",
	"Roto Prize Money": "Moti-Magot",
	"Roto Exp. Points": "Moti-Exp",
	"Roto Friendship": "Moti-Cœur",
	"Roto Encounter": "Moti-Appât",
	"Roto Stealth": "Moti-Camouflage",
	"Roto HP Restore": "Moti-Récup' PV",
	"Roto PP Restore": "Moti-Récup' PP",
	"Roto Boost": "Moti-Soutien",
	"Roto Catch": "Moti-Capture",
	"Health Candy": "Bonbon Santé S",
	"Mighty Candy": "Bonbon Force S",
	"Tough Candy": "Bonbon Armure S",
	"Smart Candy": "Bonbon Esprit S",
	"Courage Candy": "Bonbon Mental S",
	"Quick Candy": "Bonbon Sprint S",
	"Health Candy L": "Bonbon Santé M",
	"Mighty Candy L": "Bonbon Force M",
	"Tough Candy L": "Bonbon Armure M",
	"Smart Candy L": "Bonbon Esprit M",
	"Courage Candy L": "Bonbon Mental M",
	"Quick Candy L": "Bonbon Sprint M",
	"Health Candy XL": "Bonbon Santé L",
	"Mighty Candy XL": "Bonbon Force L",
	"Tough Candy XL": "Bonbon Armure L",
	"Smart Candy XL": "Bonbon Esprit L",
	"Courage Candy XL": "Bonbon Mental L",
	"Quick Candy XL": "Bonbon Sprint L",
	"Bulbasaur Candy": "Bonbon Bulbizarre",
	"Charmander Candy": "Bonbon Salamèche",
	"Squirtle Candy": "Bonbon Carapuce",
	"Caterpie Candy": "Bonbon Chenipan",
	"Weedle Candy": "Bonbon Aspicot",
	"Pidgey Candy": "Bonbon Roucool",
	"Rattata Candy": "Bonbon Rattata",
	"Spearow Candy": "Bonbon Piafabec",
	"Ekans Candy": "Bonbon Abo",
	"Pikachu Candy": "Bonbon Pikachu",
	"Sandshrew Candy": "Bonbon Sabelette",
	"Nidoran♀ Candy": "Bonbon Nidoran♀",
	"Nidoran♂ Candy": "Bonbon Nidoran♂",
	"Clefairy Candy": "Bonbon Mélofée",
	"Vulpix Candy": "Bonbon Goupix",
	"Jigglypuff Candy": "Bonbon Rondoudou",
	"Zubat Candy": "Bonbon Nosferapti",
	"Oddish Candy": "Bonbon Mystherbe",
	"Paras Candy": "Bonbon Paras",
	"Venonat Candy": "Bonbon Mimitoss",
	"Diglett Candy": "Bonbon Taupiqueur",
	"Meowth Candy": "Bonbon Miaouss",
	"Psyduck Candy": "Bonbon Psykokwak",
	"Mankey Candy": "Bonbon Férosinge",
	"Growlithe Candy": "Bonbon Caninos",
	"Poliwag Candy": "Bonbon Ptitard",
	"Abra Candy": "Bonbon Abra",
	"Machop Candy": "Bonbon Machoc",
	"Bellsprout Candy": "Bonbon Chétiflor",
	"Tentacool Candy": "Bonbon Tentacool",
	"Geodude Candy": "Bonbon Racaillou",
	"Ponyta Candy": "Bonbon Ponyta",
	"Slowpoke Candy": "Bonbon Ramoloss",
	"Magnemite Candy": "Bonbon Magnéti",
	"Farfetch'd Candy": "Bonbon Canarticho",
	"Doduo Candy": "Bonbon Doduo",
	"Seel Candy": "Bonbon Otaria",
	"Grimer Candy": "Bonbon Tadmorv",
	"Shellder Candy": "Bonbon Kokiyas",
	"Gastly Candy": "Bonbon Fantominus",
	"Onix Candy": "Bonbon Onix",
	"Drowzee Candy": "Bonbon Soporifik",
	"Krabby Candy": "Bonbon Krabby",
	"Voltorb Candy": "Bonbon Voltorbe",
	"Exeggcute Candy": "Bonbon Noeunoeuf",
	"Cubone Candy": "Bonbon Osselait",
	"Hitmonlee Candy": "Bonbon Kicklee",
	"Hitmonchan Candy": "Bonbon Tygnon",
	"Lickitung Candy": "Bonbon Excelangue",
	"Koffing Candy": "Bonbon Smogo",
	"Rhyhorn Candy": "Bonbon Rhinocorne",
	"Chansey Candy": "Bonbon Leveinard",
	"Tangela Candy": "Bonbon Saquedeneu",
	"Kangaskhan Candy": "Bonbon Kangourex",
	"Horsea Candy": "Bonbon Hypotrempe",
	"Goldeen Candy": "Bonbon Poissirène",
	"Staryu Candy": "Bonbon Stari",
	"Mr. Mime Candy": "Bonbon M. Mime",
	"Scyther Candy": "Bonbon Insécateur",
	"Jynx Candy": "Bonbon Lippoutou",
	"Electabuzz Candy": "Bonbon Élektek",
	"Pinsir Candy": "Bonbon Scarabrute",
	"Tauros Candy": "Bonbon Tauros",
	"Magikarp Candy": "Bonbon Magicarpe",
	"Lapras Candy": "Bonbon Lokhlass",
	"Ditto Candy": "Bonbon Métamorph",
	"Eevee Candy": "Bonbon Évoli",
	"Porygon Candy": "Bonbon Porygon",
	"Omanyte Candy": "Bonbon Amonita",
	"Kabuto Candy": "Bonbon Kabuto",
	"Aerodactyl Candy": "Bonbon Ptéra",
	"Snorlax Candy": "Bonbon Ronflex",
	"Articuno Candy": "Bonbon Artikodin",
	"Zapdos Candy": "Bonbon Électhor",
	"Moltres Candy": "Bonbon Sulfura",
	"Dratini Candy": "Bonbon Minidraco",
	"Mewtwo Candy": "Bonbon Mewtwo",
	"Mew Candy": "Bonbon Mew",
	"Meltan Candy": "Bonbon Meltan",
	"Magmar Candy": "Bonbon Magmar",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"Endorsement": "Recommandation",
	"Pokémon Box Link": "Boîte Pokémon",
	"Wishing Star": "Étoile Vœu",
	"Dynamax Band": "Poignet Dynamax",
	"???": "???",
	"???": "???",
	"Fishing Rod": "Canne à Pêche",
	"Rotom Bike": "Moticyclette",
	"???": "???",
	"???": "???",
	"Sausages": "Saucisses",
	"Bob's Food Tin": "Conserve de Bob",
	"Bach's Food Tin": "Conserve de Bach",
	"Tin of Beans": "Haricots",
	"Bread": "Pain de Mie",
	"Pasta": "Pâtes",
	"Mixed Mushrooms": "Champignons",
	"Smoke-Poke Tail": "Queue Fumée",
	"Large Leek": "Gros Poireau",
	"Fancy Apple": "Pomme Juteuse",
	"Brittle Bones": "Os à Moelle",
	"Pack of Potatoes": "Pommes de Terre",
	"Pungent Root": "Tubercule",
	"Salad Mix": "Légumes",
	"Fried Food": "Fritures",
	"Boiled Egg": "Œuf Dur",
	"Camping Gear": "Kit de Camping",
	"???": "???",
	"???": "???",
	"Rusted Sword": "Épée Rouillée",
	"Rusted Shield": "Bouclier Rouillé",
	"Fossilized Bird": "Fossile Oiseau",
	"Fossilized Fish": "Fossile Poisson",
	"Fossilized Drake": "Fossile Dragon",
	"Fossilized Dino": "Fossile Aileron",
	"Strawberry Sweet": "Fraise en Sucre",
	"Love Sweet": "Cœur en Sucre",
	"Berry Sweet": "Baie en Sucre",
	"Clover Sweet": "Trèfle en Sucre",
	"Flower Sweet": "Fleur en Sucre",
	"Star Sweet": "Étoile en Sucre",
	"Ribbon Sweet": "Ruban en Sucre",
	"Sweet Apple": "Pomme Sucrée",
	"Tart Apple": "Pomme Acidulée",
	"Throat Spray": "Spray Gorge",
	"Eject Pack": "Sac Fuite",
	"Heavy-Duty Boots": "Grosses Bottes",
	"Blunder Policy": "Assurance Échec",
	"Room Service": "Chariot Distordu",
	"Utility Umbrella": "Parapluie Solide",
	"Exp. Candy XS": "Bonbon Exp. XS",
	"Exp. Candy S": "Bonbon Exp. S",
	"Exp. Candy M": "Bonbon Exp. M",
	"Exp. Candy L": "Bonbon Exp. L",
	"Exp. Candy XL": "Bonbon Exp. XL",
	"Dynamax Candy": "Bonbon Dynamax",
	"TR00": "DT00",
	"TR01": "DT01",
	"TR02": "DT02",
	"TR03": "DT03",
	"TR04": "DT04",
	"TR05": "DT05",
	"TR06": "DT06",
	"TR07": "DT07",
	"TR08": "DT08",
	"TR09": "DT09",
	"TR10": "DT10",
	"TR11": "DT11",
	"TR12": "DT12",
	"TR13": "DT13",
	"TR14": "DT14",
	"TR15": "DT15",
	"TR16": "DT16",
	"TR17": "DT17",
	"TR18": "DT18",
	"TR19": "DT19",
	"TR20": "DT20",
	"TR21": "DT21",
	"TR22": "DT22",
	"TR23": "DT23",
	"TR24": "DT24",
	"TR25": "DT25",
	"TR26": "DT26",
	"TR27": "DT27",
	"TR28": "DT28",
	"TR29": "DT29",
	"TR30": "DT30",
	"TR31": "DT31",
	"TR32": "DT32",
	"TR33": "DT33",
	"TR34": "DT34",
	"TR35": "DT35",
	"TR36": "DT36",
	"TR37": "DT37",
	"TR38": "DT38",
	"TR39": "DT39",
	"TR40": "DT40",
	"TR41": "DT41",
	"TR42": "DT42",
	"TR43": "DT43",
	"TR44": "DT44",
	"TR45": "DT45",
	"TR46": "DT46",
	"TR47": "DT47",
	"TR48": "DT48",
	"TR49": "DT49",
	"TR50": "DT50",
	"TR51": "DT51",
	"TR52": "DT52",
	"TR53": "DT53",
	"TR54": "DT54",
	"TR55": "DT55",
	"TR56": "DT56",
	"TR57": "DT57",
	"TR58": "DT58",
	"TR59": "DT59",
	"TR60": "DT60",
	"TR61": "DT61",
	"TR62": "DT62",
	"TR63": "DT63",
	"TR64": "DT64",
	"TR65": "DT65",
	"TR66": "DT66",
	"TR67": "DT67",
	"TR68": "DT68",
	"TR69": "DT69",
	"TR70": "DT70",
	"TR71": "DT71",
	"TR72": "DT72",
	"TR73": "DT73",
	"TR74": "DT74",
	"TR75": "DT75",
	"TR76": "DT76",
	"TR77": "DT77",
	"TR78": "DT78",
	"TR79": "DT79",
	"TR80": "DT80",
	"TR81": "DT81",
	"TR82": "DT82",
	"TR83": "DT83",
	"TR84": "DT84",
	"TR85": "DT85",
	"TR86": "DT86",
	"TR87": "DT87",
	"TR88": "DT88",
	"TR89": "DT89",
	"TR90": "DT90",
	"TR91": "DT91",
	"TR92": "DT92",
	"TR93": "DT93",
	"TR94": "DT94",
	"TR95": "DT95",
	"TR96": "DT96",
	"TR97": "DT97",
	"TR98": "DT98",
	"TR99": "DT99",
	"TM00": "CT00",
	"Lonely Mint": "Aromate Solo",
	"Adamant Mint": "Aromate Rigide",
	"Naughty Mint": "Aromate Mauvais",
	"Brave Mint": "Aromate Brave",
	"Bold Mint": "Aromate Assuré",
	"Impish Mint": "Aromate Malin",
	"Lax Mint": "Aromate Lâche",
	"Relaxed Mint": "Aromate Relax",
	"Modest Mint": "Aromate Modeste",
	"Mild Mint": "Aromate Doux",
	"Rash Mint": "Aromate Foufou",
	"Quiet Mint": "Aromate Discret",
	"Calm Mint": "Aromate Calme",
	"Gentle Mint": "Aromate Gentil",
	"Careful Mint": "Aromate Prudent",
	"Sassy Mint": "Aromate Malpoli",
	"Timid Mint": "Aromate Timide",
	"Hasty Mint": "Aromate Pressé",
	"Jolly Mint": "Aromate Jovial",
	"Naive Mint": "Aromate Naïf",
	"Serious Mint": "Aromate Sérieux",
	"Wishing Piece": "Morceau Vœu",
	"Cracked Pot": "Théière Fêlée",
	"Chipped Pot": "Théière Ébréchée",
	"Hi-tech Earbuds": "Bouchons Audio",
	"Fruit Bunch": "Fruits",
	"Moomoo Cheese": "Fromage Meumeu",
	"Spice Mix": "Épices",
	"Fresh Cream": "Crème Fraîche",
	"Packaged Curry": "Curry Instantané",
	"Coconut Milk": "Lait de Coco",
	"Instant Noodles": "Nouilles",
	"Precooked Burger": "Steak Haché",
	"Gigantamix": "Poudre Gigamax",
	"Wishing Chip": "Fragment Vœu",
	"Rotom Bike": "Moticyclette",
	"Catching Charm": "Charme Stabilité",
	"???": "???",
	"Old Letter": "Lettre Jaunie",
	"Band Autograph": "Dédicace",
	"Sonia's Book": "Livre de Sonya",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"Rotom Catalog": "Moti-Catalogue",
	"★And458": "★And458",
	"★And15": "★And15",
	"★And337": "★And337",
	"★And603": "★And603",
	"★And390": "★And390",
	"★Sgr6879": "★Sgr6879",
	"★Sgr6859": "★Sgr6859",
	"★Sgr6913": "★Sgr6913",
	"★Sgr7348": "★Sgr7348",
	"★Sgr7121": "★Sgr7121",
	"★Sgr6746": "★Sgr6746",
	"★Sgr7194": "★Sgr7194",
	"★Sgr7337": "★Sgr7337",
	"★Sgr7343": "★Sgr7343",
	"★Sgr6812": "★Sgr6812",
	"★Sgr7116": "★Sgr7116",
	"★Sgr7264": "★Sgr7264",
	"★Sgr7597": "★Sgr7597",
	"★Del7882": "★Del7882",
	"★Del7906": "★Del7906",
	"★Del7852": "★Del7852",
	"★Psc596": "★Psc596",
	"★Psc361": "★Psc361",
	"★Psc510": "★Psc510",
	"★Psc437": "★Psc437",
	"★Psc8773": "★Psc8773",
	"★Lep1865": "★Lep1865",
	"★Lep1829": "★Lep1829",
	"★Boo5340": "★Boo5340",
	"★Boo5506": "★Boo5506",
	"★Boo5435": "★Boo5435",
	"★Boo5602": "★Boo5602",
	"★Boo5733": "★Boo5733",
	"★Boo5235": "★Boo5235",
	"★Boo5351": "★Boo5351",
	"★Hya3748": "★Hya3748",
	"★Hya3903": "★Hya3903",
	"★Hya3418": "★Hya3418",
	"★Hya3482": "★Hya3482",
	"★Hya3845": "★Hya3845",
	"★Eri1084": "★Eri1084",
	"★Eri472": "★Eri472",
	"★Eri1666": "★Eri1666",
	"★Eri897": "★Eri897",
	"★Eri1231": "★Eri1231",
	"★Eri874": "★Eri874",
	"★Eri1298": "★Eri1298",
	"★Eri1325": "★Eri1325",
	"★Eri984": "★Eri984",
	"★Eri1464": "★Eri1464",
	"★Eri1393": "★Eri1393",
	"★Eri850": "★Eri850",
	"★Tau1409": "★Tau1409",
	"★Tau1457": "★Tau1457",
	"★Tau1165": "★Tau1165",
	"★Tau1791": "★Tau1791",
	"★Tau1910": "★Tau1910",
	"★Tau1346": "★Tau1346",
	"★Tau1373": "★Tau1373",
	"★Tau1412": "★Tau1412",
	"★CMa2491": "★CMa2491",
	"★CMa2693": "★CMa2693",
	"★CMa2294": "★CMa2294",
	"★CMa2827": "★CMa2827",
	"★CMa2282": "★CMa2282",
	"★CMa2618": "★CMa2618",
	"★CMa2657": "★CMa2657",
	"★CMa2646": "★CMa2646",
	"★UMa4905": "★UMa4905",
	"★UMa4301": "★UMa4301",
	"★UMa5191": "★UMa5191",
	"★UMa5054": "★UMa5054",
	"★UMa4295": "★UMa4295",
	"★UMa4660": "★UMa4660",
	"★UMa4554": "★UMa4554",
	"★UMa4069": "★UMa4069",
	"★UMa3569": "★UMa3569",
	"★UMa3323": "★UMa3323",
	"★UMa4033": "★UMa4033",
	"★UMa4377": "★UMa4377",
	"★UMa4375": "★UMa4375",
	"★UMa4518": "★UMa4518",
	"★UMa3594": "★UMa3594",
	"★Vir5056": "★Vir5056",
	"★Vir4825": "★Vir4825",
	"★Vir4932": "★Vir4932",
	"★Vir4540": "★Vir4540",
	"★Vir4689": "★Vir4689",
	"★Vir5338": "★Vir5338",
	"★Vir4910": "★Vir4910",
	"★Vir5315": "★Vir5315",
	"★Vir5359": "★Vir5359",
	"★Vir5409": "★Vir5409",
	"★Vir5107": "★Vir5107",
	"★Ari617": "★Ari617",
	"★Ari553": "★Ari553",
	"★Ari546": "★Ari546",
	"★Ari951": "★Ari951",
	"★Ori1713": "★Ori1713",
	"★Ori2061": "★Ori2061",
	"★Ori1790": "★Ori1790",
	"★Ori1903": "★Ori1903",
	"★Ori1948": "★Ori1948",
	"★Ori2004": "★Ori2004",
	"★Ori1852": "★Ori1852",
	"★Ori1879": "★Ori1879",
	"★Ori1899": "★Ori1899",
	"★Ori1543": "★Ori1543",
	"★Cas21": "★Cas21",
	"★Cas168": "★Cas168",
	"★Cas403": "★Cas403",
	"★Cas153": "★Cas153",
	"★Cas542": "★Cas542",
	"★Cas219": "★Cas219",
	"★Cas265": "★Cas265",
	"★Cnc3572": "★Cnc3572",
	"★Cnc3208": "★Cnc3208",
	"★Cnc3461": "★Cnc3461",
	"★Cnc3449": "★Cnc3449",
	"★Cnc3429": "★Cnc3429",
	"★Cnc3627": "★Cnc3627",
	"★Cnc3268": "★Cnc3268",
	"★Cnc3249": "★Cnc3249",
	"★Com4968": "★Com4968",
	"★Crv4757": "★Crv4757",
	"★Crv4623": "★Crv4623",
	"★Crv4662": "★Crv4662",
	"★Crv4786": "★Crv4786",
	"★Aur1708": "★Aur1708",
	"★Aur2088": "★Aur2088",
	"★Aur1605": "★Aur1605",
	"★Aur2095": "★Aur2095",
	"★Aur1577": "★Aur1577",
	"★Aur1641": "★Aur1641",
	"★Aur1612": "★Aur1612",
	"★Pav7790": "★Pav7790",
	"★Cet911": "★Cet911",
	"★Cet681": "★Cet681",
	"★Cet188": "★Cet188",
	"★Cet539": "★Cet539",
	"★Cet804": "★Cet804",
	"★Cep8974": "★Cep8974",
	"★Cep8162": "★Cep8162",
	"★Cep8238": "★Cep8238",
	"★Cep8417": "★Cep8417",
	"★Cen5267": "★Cen5267",
	"★Cen5288": "★Cen5288",
	"★Cen551": "★Cen551",
	"★Cen5459": "★Cen5459",
	"★Cen5460": "★Cen5460",
	"★CMi2943": "★CMi2943",
	"★CMi2845": "★CMi2845",
	"★Equ8131": "★Equ8131",
	"★Vul7405": "★Vul7405",
	"★UMi424": "★UMi424",
	"★UMi5563": "★UMi5563",
	"★UMi5735": "★UMi5735",
	"★UMi6789": "★UMi6789",
	"★Crt4287": "★Crt4287",
	"★Lyr7001": "★Lyr7001",
	"★Lyr7178": "★Lyr7178",
	"★Lyr7106": "★Lyr7106",
	"★Lyr7298": "★Lyr7298",
	"★Ara6585": "★Ara6585",
	"★Sco6134": "★Sco6134",
	"★Sco6527": "★Sco6527",
	"★Sco6553": "★Sco6553",
	"★Sco5953": "★Sco5953",
	"★Sco5984": "★Sco5984",
	"★Sco6508": "★Sco6508",
	"★Sco6084": "★Sco6084",
	"★Sco5944": "★Sco5944",
	"★Sco6630": "★Sco6630",
	"★Sco6027": "★Sco6027",
	"★Sco6247": "★Sco6247",
	"★Sco6252": "★Sco6252",
	"★Sco5928": "★Sco5928",
	"★Sco6241": "★Sco6241",
	"★Sco6165": "★Sco6165",
	"★Tri544": "★Tri544",
	"★Leo3982": "★Leo3982",
	"★Leo4534": "★Leo4534",
	"★Leo4357": "★Leo4357",
	"★Leo4057": "★Leo4057",
	"★Leo4359": "★Leo4359",
	"★Leo4031": "★Leo4031",
	"★Leo3852": "★Leo3852",
	"★Leo3905": "★Leo3905",
	"★Leo3773": "★Leo3773",
	"★Gru8425": "★Gru8425",
	"★Gru8636": "★Gru8636",
	"★Gru8353": "★Gru8353",
	"★Lib5685": "★Lib5685",
	"★Lib5531": "★Lib5531",
	"★Lib5787": "★Lib5787",
	"★Lib5603": "★Lib5603",
	"★Pup3165": "★Pup3165",
	"★Pup3185": "★Pup3185",
	"★Pup3045": "★Pup3045",
	"★Cyg7924": "★Cyg7924",
	"★Cyg7417": "★Cyg7417",
	"★Cyg7796": "★Cyg7796",
	"★Cyg8301": "★Cyg8301",
	"★Cyg7949": "★Cyg7949",
	"★Cyg7528": "★Cyg7528",
	"★Oct7228": "★Oct7228",
	"★Col1956": "★Col1956",
	"★Col2040": "★Col2040",
	"★Col2177": "★Col2177",
	"★Gem2990": "★Gem2990",
	"★Gem2891": "★Gem2891",
	"★Gem2421": "★Gem2421",
	"★Gem2473": "★Gem2473",
	"★Gem2216": "★Gem2216",
	"★Gem2777": "★Gem2777",
	"★Gem2650": "★Gem2650",
	"★Gem2286": "★Gem2286",
	"★Gem2484": "★Gem2484",
	"★Gem2930": "★Gem2930",
	"★Peg8775": "★Peg8775",
	"★Peg8781": "★Peg8781",
	"★Peg39": "★Peg39",
	"★Peg8308": "★Peg8308",
	"★Peg8650": "★Peg8650",
	"★Peg8634": "★Peg8634",
	"★Peg8684": "★Peg8684",
	"★Peg8450": "★Peg8450",
	"★Peg8880": "★Peg8880",
	"★Peg8905": "★Peg8905",
	"★Oph6556": "★Oph6556",
	"★Oph6378": "★Oph6378",
	"★Oph6603": "★Oph6603",
	"★Oph6149": "★Oph6149",
	"★Oph6056": "★Oph6056",
	"★Oph6075": "★Oph6075",
	"★Ser5854": "★Ser5854",
	"★Ser7141": "★Ser7141",
	"★Ser5879": "★Ser5879",
	"★Her6406": "★Her6406",
	"★Her6148": "★Her6148",
	"★Her6410": "★Her6410",
	"★Her6526": "★Her6526",
	"★Her6117": "★Her6117",
	"★Her6008": "★Her6008",
	"★Per936": "★Per936",
	"★Per1017": "★Per1017",
	"★Per1131": "★Per1131",
	"★Per1228": "★Per1228",
	"★Per834": "★Per834",
	"★Per941": "★Per941",
	"★Phe99": "★Phe99",
	"★Phe338": "★Phe338",
	"★Vel3634": "★Vel3634",
	"★Vel3485": "★Vel3485",
	"★Vel3734": "★Vel3734",
	"★Aqr8232": "★Aqr8232",
	"★Aqr8414": "★Aqr8414",
	"★Aqr8709": "★Aqr8709",
	"★Aqr8518": "★Aqr8518",
	"★Aqr7950": "★Aqr7950",
	"★Aqr8499": "★Aqr8499",
	"★Aqr8610": "★Aqr8610",
	"★Aqr8264": "★Aqr8264",
	"★Cru4853": "★Cru4853",
	"★Cru4730": "★Cru4730",
	"★Cru4763": "★Cru4763",
	"★Cru4700": "★Cru4700",
	"★Cru4656": "★Cru4656",
	"★PsA8728": "★PsA8728",
	"★TrA6217": "★TrA6217",
	"★Cap7776": "★Cap7776",
	"★Cap7754": "★Cap7754",
	"★Cap8278": "★Cap8278",
	"★Cap8322": "★Cap8322",
	"★Cap7773": "★Cap7773",
	"★Sge7479": "★Sge7479",
	"★Car2326": "★Car2326",
	"★Car3685": "★Car3685",
	"★Car3307": "★Car3307",
	"★Car3699": "★Car3699",
	"★Dra5744": "★Dra5744",
	"★Dra5291": "★Dra5291",
	"★Dra6705": "★Dra6705",
	"★Dra6536": "★Dra6536",
	"★Dra7310": "★Dra7310",
	"★Dra6688": "★Dra6688",
	"★Dra4434": "★Dra4434",
	"★Dra6370": "★Dra6370",
	"★Dra7462": "★Dra7462",
	"★Dra6396": "★Dra6396",
	"★Dra6132": "★Dra6132",
	"★Dra6636": "★Dra6636",
	"★CVn4915": "★CVn4915",
	"★CVn4785": "★CVn4785",
	"★CVn4846": "★CVn4846",
	"★Aql7595": "★Aql7595",
	"★Aql7557": "★Aql7557",
	"★Aql7525": "★Aql7525",
	"★Aql7602": "★Aql7602",
	"★Aql7235": "★Aql7235",
	"Max Honey": "Maxi Miel",
	"Max Mushrooms": "Maxi Champi",
	"Galarica Twig": "Branche Galanoa",
	"Galarica Cuff": "Bracelet Galanoa",
	"Style Card": "Carte Élégance",
	"Armor Pass": "Pass Isolarmure",
	"Rotom Bike": "Moticyclette",
	"Rotom Bike": "Moticyclette",
	"Exp. Charm": "Charme Exp",
	"Armorite Ore": "Armurium",
	"Mark Charm": "Charme Insigne",
	"Reins of Unity": "Rênes de l'Unité",
	"Reins of Unity": "Rênes de l'Unité",
	"Galarica Wreath": "Couronne Galanoa",
	"Legendary Clue 1": "Note Légende 1",
	"Legendary Clue 2": "Note Légende 2",
	"Legendary Clue 3": "Note Légende 3",
	"Legendary Clue?": "Note Légende (?)",
	"Crown Pass": "Pass Couronneige",
	"Wooden Crown": "Couronne en Bois",
	"Radiant Petal": "Pétale Brillant",
	"White Mane Hair": "Crins Blancs",
	"Black Mane Hair": "Crins Sombres",
	"Iceroot Carrot": "Carotte Gelée",
	"Shaderoot Carrot": "Carotte Sombre",
	"Dynite Ore": "Dynamaxium",
	"Carrot Seeds": "Graines Carotte",
	"Ability Patch": "Patch Talent",
	"Reins of Unity": "Rênes de l'Unité",
	"Time Balm": "Pacifi-Temps",
	"Space Balm": "Pacifi-Espace",
	"Mysterious Balm": "Pacifisphère",
	"Linking Cord": "Fil de Liaison",
	"Hometown Muffin": "Muffin Tradition",
	"Apricorn": "Noigrume",
	"Jubilife Muffin": "Rusti-Muffin",
	"Aux Powerguard": "Double Extra",
	"Dire Hit": "Muscle +",
	"Choice Dumpling": "Papillote Choix",
	"Twice-Spiced Radish": "Bouchée Double",
	"Swap Snack": "En-cas Contraire",
	"Caster Fern": "Feuille Ronde",
	"Seed of Mastery": "Graine Maîtrise",
	"Poké Ball": "Poké Ball",
	"???": "???",
	"Eternal Ice": "Glaçon Éternel",
	"Uxie's Claw": "Griffe de Créhelf",
	"Azelf's Fang": "Croc de Créfadet",
	"Mesprit's Plume": "Aile de Créfollet",
	"Tumblestone": "Galet",
	"Celestica Flute": "Flûte Céleste",
	"Remedy": "Remède",
	"Fine Remedy": "Super Remède",
	"Dazzling Honey": "Miel Kibrille",
	"Hearty Grains": "Riz Zélé",
	"Plump Beans": "Fève Dodue",
	"Springy Mushroom": "Champi Toumou",
	"Crunchy Salt": "Sel Rochedur",
	"Wood": "Bois",
	"King's Leaf": "Herbe Souveraine",
	"Marsh Balm": "Pacifi-Marais",
	"Poké Ball": "Poké Ball",
	"Great Ball": "Super Ball",
	"Ultra Ball": "Hyper Ball",
	"Feather Ball": "Plume Ball",
	"Pokéshi Doll": "Poupée Pokéshi",
	"???": "???",
	"Smoke Bomb": "Bombe Aveuglante",
	"Scatter Bang": "Sachet Pétarade",
	"Sticky Glob": "Boule Gluante",
	"Star Piece": "Morceau d'Étoile",
	"Mushroom Cake": "Appât Toumou",
	"Bugwort": "Plante Répulsive",
	"Honey Cake": "Appât Kibrille",
	"Grain Cake": "Appât Zélé",
	"Bean Cake": "Appât Dodu",
	"Salt Cake": "Appât Rochedur",
	"Potion": "Potion",
	"Super Potion": "Super Potion",
	"Hyper Potion": "Hyper Potion",
	"Max Potion": "Potion Max",
	"Full Restore": "Guérison",
	"Remedy": "Remède",
	"Fine Remedy": "Super Remède",
	"Superb Remedy": "Hyper Remède",
	"Old Gateau": "Vieux Gâteau",
	"Jubilife Muffin": "Rusti-Muffin",
	"Full Heal": "Total Soin",
	"Revive": "Rappel",
	"Max Revive": "Rappel Max",
	"Max Ether": "Soin PP",
	"Max Elixir": "Maxi Soin PP",
	"Stealth Spray": "Solution Furtive",
	"???": "???",
	"Aux Power": "Offensive Extra",
	"Aux Guard": "Défense Extra",
	"Dire Hit": "Muscle +",
	"Aux Evasion": "Esquive Extra",
	"Aux Powerguard": "Double Extra",
	"Forest Balm": "Pacifi-Forêt",
	"Iron Chunk": "Fragment de Fer",
	"???": "???",
	"Black Tumblestone": "Galet Noir",
	"Sky Tumblestone": "Galet Azur",
	"???": "???",
	"Ball of Mud": "Boule de Boue",
	"???": "???",
	"Pop Pod": "Pétaralgue",
	"Sootfoot Root": "Rutabagaz",
	"Spoiled Apricorn": "Noigrume Rongé",
	"Snowball": "Boule de Neige",
	"Sticky Glob": "Boule Gluante",
	"Black Augurite": "Obsidienne",
	"Peat Block": "Bloc de Tourbe",
	"Stealth Spray": "Solution Furtive",
	"Medicinal Leek": "Soignon",
	"Vivichoke": "Bourgeon Vivace",
	"Pep-Up Plant": "Plante PP",
	"???": "???",
	"???": "???",
	"Tempting Charm B": "Remplamulette 2",
	"Tempting Charm P": "Remplamulette 3",
	"Swordcap": "Fortichampi",
	"Iron Barktongue": "Carapachampi",
	"Doppel Bonnets": "Champinja",
	"Direshroom": "Champiscoto",
	"Sand Radish": "Radis des Plages",
	"Tempting Charm T": "Remplamulette 4",
	"Tempting Charm Y": "Remplamulette 5",
	"Candy Truffle": "Truffe Sucrée",
	"Cake-Lure Base": "Appâte",
	"Poké Ball": "Poké Ball",
	"Great Ball": "Super Ball",
	"Ultra Ball": "Hyper Ball",
	"Feather Ball": "Plume Ball",
	"???": "???",
	"???": "???",
	"Scatter Bang": "Sachet Pétarade",
	"Smoke Bomb": "Bombe Aveuglante",
	"???": "???",
	"???": "???",
	"Pokéshi Doll": "Poupée Pokéshi",
	"Volcano Balm": "Pacifi-Volcan",
	"Mountain Balm": "Pacifi-Montagne",
	"Snow Balm": "Pacifi-Neige",
	"Honey Cake": "Appât Kibrille",
	"Grain Cake": "Appât Zélé",
	"Bean Cake": "Appât Dodu",
	"Mushroom Cake": "Appât Toumou",
	"Salt Cake": "Appât Rochedur",
	"Swap Snack": "En-cas Contraire",
	"Choice Dumpling": "Papillote Choix",
	"Twice-Spiced Radish": "Bouchée Double",
	"Survival Charm R": "Enduramulette 1",
	"Survival Charm B": "Enduramulette 2",
	"Survival Charm P": "Enduramulette 3",
	"Survival Charm T": "Enduramulette 4",
	"Survival Charm Y": "Enduramulette 5",
	"Torn Journal": "Journal Déchiré",
	"Warding Charm R": "Zenamulette 1",
	"Warding Charm B": "Zenamulette 2",
	"Warding Charm P": "Zenamulette 3",
	"Warding Charm T": "Zenamulette 4",
	"Warding Charm Y": "Zenamulette 5",
	"Wall Fragment": "Fragment de Mur",
	"Basculegion Food": "Appâragruel",
	"Old Journal": "Vieux Journal",
	"Wing Ball": "Envol Ball",
	"Jet Ball": "Propulse Ball",
	"Heavy Ball": "Masse Ball",
	"Leaden Ball": "Mégamasse Ball",
	"Gigaton Ball": "Gigamasse Ball",
	"Wing Ball": "Envol Ball",
	"Jet Ball": "Propulse Ball",
	"Heavy Ball": "Masse Ball",
	"Hopo Berry": "Baie Bouhlon",
	"Superb Remedy": "Hyper Remède",
	"Aux Power": "Offensive Extra",
	"Aux Guard": "Défense Extra",
	"Aux Evasion": "Esquive Extra",
	"Grit Dust": "Sable Effort",
	"Grit Gravel": "Cailloux Effort",
	"Grit Pebble": "Pierre Effort",
	"Grit Rock": "Rocher Effort",
	"Secret Medicine": "Remède Secret",
	"Tempting Charm R": "Remplamulette 1",
	"Lost Satchel": "Objet Perdu",
	"Lost Satchel": "Objet Perdu",
	"Lost Satchel": "Objet Perdu",
	"Lost Satchel": "Objet Perdu",
	"Lost Satchel": "Objet Perdu",
	"???": "???",
	"Origin Ball": "Origine Ball",
	"???": "???",
	"???": "???",
	"???": "???",
	"???": "???",
	"Origin Ore": "Minerai Origine",
	"Adamant Crystal": "Globe Adamant",
	"Lustrous Globe": "Globe Perlé",
	"Griseous Core": "Globe Platiné",
	"Blank Plate": "Plaque Renouveau",
	"???": "???",
	"Crafting Kit": "Boîte à Outils",
	"Leaden Ball": "Mégamasse Ball",
	"Gigaton Ball": "Gigamasse Ball",
	"Strange Ball": "Étrange Ball",
	"Pokédex": "Pokédex",
	"Old Verse 1": "Vieux Poème (1)",
	"Old Verse 2": "Vieux Poème (2)",
	"Old Verse 3": "Vieux Poème (3)",
	"Old Verse 4": "Vieux Poème (4)",
	"???": "???",
	"Old Verse 5": "Vieux Poème (5)",
	"Old Verse 6": "Vieux Poème (6)",
	"Old Verse 7": "Vieux Poème (7)",
	"Old Verse 8": "Vieux Poème (8)",
	"Old Verse 9": "Vieux Poème (9)",
	"Old Verse 10": "Vieux Poème (10)",
	"Old Verse 11": "Vieux Poème (11)",
	"Old Verse 12": "Vieux Poème (12)",
	"Old Verse 13": "Vieux Poème (13)",
	"Old Verse 14": "Vieux Poème (14)",
	"Old Verse 15": "Vieux Poème (15)",
	"Old Verse 16": "Vieux Poème (16)",
	"Old Verse 17": "Vieux Poème (17)",
	"Old Verse 18": "Vieux Poème (18)",
	"Old Verse 19": "Vieux Poème (19)",
	"Old Verse 20": "Vieux Poème (20)",
	"Mysterious Shard S": "Éclat Étrange S",
	"Mysterious Shard L": "Éclat Étrange L",
	"Digger Drill": "Foreuse",
	"Kanto Slate": "Tablette Kanto",
	"Johto Slate": "Tablette Johto",
	"Soul Slate": "Tablette Cœur",
	"Rainbow Slate": "Tablette Arc-en-ciel",
	"Squall Slate": "Tablette Tempête",
	"Oceanic Slate": "Tablette Océans",
	"Tectonic Slate": "Tablette Continents",
	"Stratospheric Slate": "Tablette Cieux",
	"Genome Slate": "Tablette Génétique",
	"Discovery Slate": "Tablette Guides",
	"Distortion Slate": "Tablette Distorsion",
	"DS Sounds": "Lecteur DS",
	"Legend Plate": "Plaque Légende",
	"Rotom Phone": "Motismart",
	"Sandwich": "Sandwich",
	"Koraidon's Poké Ball": "Poké Ball de Koraidon",
	"Miraidon's Poké Ball": "Poké Ball de Miraidon",
	"Tera Orb": "Orbe Téracristal",
	"Scarlet Book": "Livre Écarlate",
	"Violet Book": "Livre Violet",
	"Kofu's Wallet": "Portefeuille de Kombu",
	"Tiny Bamboo Shoot": "Petit Bambou",
	"Big Bamboo Shoot": "Gros Bambou",
	"Scroll of Darkness": "Rouleau des Ténèbres",
	"Scroll of Waters": "Rouleau de l'Eau",
	"Malicious Armor": "Armure de la Rancune",
	"Normal Tera Shard": "Téra-Éclat Normal",
	"Fire Tera Shard": "Téra-Éclat Feu",
	"Water Tera Shard": "Téra-Éclat Eau",
	"Electric Tera Shard": "Téra-Éclat Électrik",
	"Grass Tera Shard": "Téra-Éclat Plante",
	"Ice Tera Shard": "Téra-Éclat Glace",
	"Fighting Tera Shard": "Téra-Éclat Combat",
	"Poison Tera Shard": "Téra-Éclat Poison",
	"Ground Tera Shard": "Téra-Éclat Sol",
	"Flying Tera Shard": "Téra-Éclat Vol",
	"Psychic Tera Shard": "Téra-Éclat Psy",
	"Bug Tera Shard": "Téra-Éclat Insecte",
	"Rock Tera Shard": "Téra-Éclat Roche",
	"Ghost Tera Shard": "Téra-Éclat Spectre",
	"Dragon Tera Shard": "Téra-Éclat Dragon",
	"Dark Tera Shard": "Téra-Éclat Ténèbres",
	"Steel Tera Shard": "Téra-Éclat Acier",
	"Fairy Tera Shard": "Téra-Éclat Fée",
	"Booster Energy": "Énergie Booster",
	"Ability Shield": "Garde-Talent",
	"Clear Amulet": "Talisman Sain",
	"Mirror Herb": "Feuille Copieuse",
	"Punching Glove": "Gant de Boxe",
	"Covert Cloak": "Cape Obscure",
	"Loaded Dice": "Dé Pipé",
	"Baguette": "Baguette",
	"Mayonnaise": "Mayonnaise",
	"Ketchup": "Ketchup",
	"Mustard": "Moutarde",
	"Butter": "Beurre",
	"Peanut Butter": "Beurre de Cacahuètes",
	"Chili Sauce": "Sauce Piquante",
	"Salt": "Sel",
	"Pepper": "Poivre",
	"Yogurt": "Yaourt",
	"Whipped Cream": "Crème Fouettée",
	"Cream Cheese": "Fromage Frais",
	"Jam": "Confiture de Baies",
	"Marmalade": "Marmelade",
	"Olive Oil": "Huile d'Olive",
	"Vinegar": "Vinaigre",
	"Sweet Herba Mystica": "Épice Secrète Sucrée",
	"Salty Herba Mystica": "Épice Secrète Salée",
	"Sour Herba Mystica": "Épice Secrète Acide",
	"Bitter Herba Mystica": "Épice Secrète Amère",
	"Spicy Herba Mystica": "Épice Secrète Corsée",
	"Lettuce": "Laitue",
	"Tomato": "Tomate",
	"Cherry Tomatoes": "Tomate Cerise",
	"Cucumber": "Concombre",
	"Pickle": "Cornichon",
	"Onion": "Oignon",
	"Red Onion": "Oignon Rouge",
	"Green Bell Pepper": "Poivron Vert",
	"Red Bell Pepper": "Poivron Rouge",
	"Yellow Bell Pepper": "Poivron Jaune",
	"Avocado": "Avocat",
	"Bacon": "Bacon",
	"Ham": "Jambon Blanc",
	"Prosciutto": "Jambon Cru",
	"Chorizo": "Chorizo Grillé",
	"Herbed Sausage": "Saucisse aux Herbes",
	"Hamburger": "Steak Haché",
	"Klawf Stick": "Bâtonnet de Craparoi",
	"Smoked Fillet": "Filet Fumé",
	"Fried Fillet": "Filet Frit",
	"Egg": "Œuf",
	"Potato Tortilla": "Tortilla",
	"Tofu": "Tofu",
	"Rice": "Riz",
	"Noodles": "Nouilles",
	"Potato Salad": "Salade de Patates",
	"Cheese": "Fromage",
	"Banana": "Banane",
	"Strawberry": "Fraise",
	"Apple": "Pomme",
	"Kiwi": "Kiwi",
	"Pineapple": "Ananas",
	"Jalapeño": "Piment",
	"Horseradish": "Raifort",
	"Curry Powder": "Curry en Poudre",
	"Wasabi": "Sauce au Wasabi",
	"Watercress": "Cresson",
	"Basil": "Basilic",
	"Venonat Fang": "Croc de Mimitoss",
	"Diglett Dirt": "Terre de Taupiqueur",
	"Meowth Fur": "Poils de Miaouss",
	"Psyduck Down": "Duvet de Psykokwak",
	"Mankey Fur": "Poils de Férosinge",
	"Growlithe Fur": "Poils de Caninos",
	"Slowpoke Claw": "Griffe de Ramoloss",
	"Magnemite Screw": "Vis de Magnéti",
	"Grimer Toxin": "Poison de Tadmorv",
	"Shellder Pearl": "Perle de Kokiyas",
	"Gastly Gas": "Gaz de Fantominus",
	"Drowzee Fur": "Poils de Soporifik",
	"Voltorb Sparks": "Électricité de Voltorbe",
	"Scyther Claw": "Griffe d'Insécateur",
	"Tauros Hair": "Poils de Tauros",
	"Magikarp Scales": "Écaille de Magicarpe",
	"Ditto Goo": "Substance de Métamorph",
	"Eevee Fur": "Poils d'Évoli",
	"Dratini Scales": "Écaille de Minidraco",
	"Pichu Fur": "Poils de Pichu",
	"Igglybuff Fluff": "Poils de Toudoudou",
	"Mareep Wool": "Laine de Wattouat",
	"Hoppip Leaf": "Feuille de Granivol",
	"Sunkern Leaf": "Feuille de Tournegrin",
	"Murkrow Bauble": "Trésor de Cornèbre",
	"Misdreavus Tears": "Larme de Feuforêve",
	"Girafarig Fur": "Poils de Girafarig",
	"Pineco Husk": "Écorce de Pomdepik",
	"Dunsparce Scales": "Écaille d'Insolourdo",
	"Qwilfish Spines": "Épine de Qwilfish",
	"Heracross Claw": "Griffe de Scarhino",
	"Sneasel Claw": "Griffe de Farfuret",
	"Teddiursa Claw": "Griffe de Teddiursa",
	"Delibird Parcel": "Provisions de Cadoizo",
	"Houndour Fang": "Croc de Malosse",
	"Phanpy Nail": "Ongle de Phanpy",
	"Stantler Hair": "Poils de Cerfrousse",
	"Larvitar Claw": "Griffe d'Embrylex",
	"Wingull Feather": "Plume de Goélise",
	"Ralts Dust": "Babiole de Tarsal",
	"Surskit Syrup": "Nectar d'Arakdo",
	"Shroomish Spores": "Spores de Balignon",
	"Slakoth Fur": "Poils de Parecool",
	"Makuhita Sweat": "Sueur de Makuhita",
	"Azurill Fur": "Poils d'Azurill",
	"Sableye Gem": "Joyau de Ténéfix",
	"Meditite Sweat": "Sueur de Méditikka",
	"Gulpin Mucus": "Mucus de Gloupti",
	"Numel Lava": "Lave de Chamallot",
	"Torkoal Coal": "Charbon de Chartor",
	"Spoink Pearl": "Perle de Spoink",
	"Cacnea Needle": "Épine de Cacnea",
	"Swablu Fluff": "Plume de Tylton",
	"Zangoose Claw": "Griffe de Mangriff",
	"Seviper Fang": "Croc de Séviper",
	"Barboach Slime": "Mucus de Barloche",
	"Shuppet Scrap": "Tissu de Polichombr",
	"Tropius Leaf": "Feuille de Tropius",
	"Snorunt Fur": "Poils de Stalgamin",
	"Luvdisc Scales": "Écaille de Lovdisc",
	"Bagon Scales": "Écaille de Draby",
	"Starly Feather": "Plume d'Étourmi",
	"Kricketot Shell": "Mue de Crikzik",
	"Shinx Fang": "Croc de Lixy",
	"Combee Honey": "Nectar d'Apitrini",
	"Pachirisu Fur": "Poils de Pachirisu",
	"Buizel Fur": "Poils de Mustébouée",
	"Shellos Mucus": "Mucus de Sancoki",
	"Drifloon Gas": "Gaz de Baudrive",
	"Stunky Fur": "Poils de Moufouette",
	"Bronzor Fragment": "Fragment d'Archéomire",
	"Bonsly Tears": "Larme de Manzaï",
	"Happiny Dust": "Babiole de Ptiravi",
	"Spiritomb Fragment": "Fragment de Spiritomb",
	"Gible Scales": "Écaille de Griknot",
	"Riolu Fur": "Poils de Riolu",
	"Hippopotas Sand": "Sable d'Hippopotas",
	"Croagunk Poison": "Poison de Cradopaud",
	"Finneon Scales": "Écaille d'Écayon",
	"Snover Berries": "Baie de Blizzi",
	"Rotom Sparks": "Électricité de Motisma",
	"Petilil Leaf": "Feuille de Chlorobule",
	"Basculin Fang": "Croc de Bargantua",
	"Sandile Claw": "Griffe de Mascaïman",
	"Zorua Fur": "Poils de Zorua",
	"Gothita Eyelash": "Cils de Scrutella",
	"Deerling Hair": "Poils de Vivaldaim",
	"Foongus Spores": "Spores de Trompignon",
	"Alomomola Mucus": "Mucus de Mamanbo",
	"Tynamo Slime": "Mucus d'Anchwatt",
	"Axew Scales": "Écaille de Coupenotte",
	"Cubchoo Fur": "Poils de Polarhume",
	"Cryogonal Ice": "Glace d'Hexagel",
	"Pawniard Blade": "Lame de Scalpion",
	"Rufflet Feather": "Plume de Furaiglon",
	"Deino Scales": "Écaille de Solochi",
	"Larvesta Fuzz": "Poils de Pyronille",
	"Fletchling Feather": "Plume de Passerouge",
	"Scatterbug Powder": "Poudre de Lépidonille",
	"Litleo Tuft": "Crinière d'Hélionceau",
	"Flabébé Pollen": "Pollen de Flabébé",
	"Flabebe Pollen": "Pollen de Flabébé",
	"Skiddo Leaf": "Feuille de Cabriolaine",
	"Skrelp Kelp": "Algue de Venalgue",
	"Clauncher Claw": "Pince de Flingouste",
	"Hawlucha Down": "Duvet de Brutalibré",
	"Dedenne Fur": "Poils de Dedenne",
	"Goomy Goo": "Mucus de Mucuscule",
	"Klefki Key": "Clé de Trousselin",
	"Bergmite Ice": "Glace de Grelaçon",
	"Noibat Fur": "Poils de Sonistrelle",
	"Yungoos Fur": "Poils de Manglouton",
	"Crabrawler Shell": "Carapace de Crabagarre",
	"Oricorio Feather": "Plume de Plumeline",
	"Rockruff Rock": "Roche de Rocabot",
	"Mareanie Spike": "Épine de Vorastérie",
	"Mudbray Mud": "Boue de Tiboudet",
	"Fomantis Leaf": "Feuille de Mimantis",
	"Salandit Gas": "Gaz de Tritox",
	"Bounsweet Sweat": "Sueur de Croquine",
	"Oranguru Fur": "Poils de Gouroutan",
	"Passimian Fur": "Poils de Quartermac",
	"Sandygast Sand": "Sable de Bacabouh",
	"Komala Claw": "Griffe de Dodoala",
	"Mimikyu Scrap": "Tissu de Mimiqui",
	"Bruxish Tooth": "Dent de Denticrisse",
	"Chewtle Claw": "Griffe de Khélocrok",
	"Skwovet Fur": "Poils de Rongourmand",
	"Arrokuda Scales": "Écaille d'Embrochet",
	"Rookidee Feather": "Plume de Minisange",
	"Toxel Sparks": "Électricité de Toxizap",
	"Falinks Sweat": "Sueur d'Hexadron",
	"Cufant Tarnish": "Rouille de Charibari",
	"Rolycoly Coal": "Charbon de Charbi",
	"Silicobra Sand": "Sable de Dunaja",
	"Indeedee Fur": "Poils de Wimessir",
	"Pincurchin Spines": "Épine de Wattapik",
	"Snom Thread": "Fil de Frissonille",
	"Impidimp Hair": "Poils de Grimalin",
	"Applin Juice": "Jus de Verpom",
	"Sinistea Chip": "Fragment de Théffroi",
	"Hatenna Dust": "Babiole de Bibichut",
	"Stonjourner Stone": "Roche de Dolman",
	"Eiscue Down": "Duvet de Bekaglaçon",
	"Dreepy Powder": "Poudre de Fantyrm",
	"Lechonk Hair": "Poils de Gourmelet",
	"Tarountula Thread": "Fil de Tissenboule",
	"Nymble Claw": "Griffe de Lilliterelle",
	"Rellor Mud": "Boue de Léboulérou",
	"Greavard Wax": "Cire de Toutombe",
	"Flittle Down": "Duvet de Flotillon",
	"Wiglett Sand": "Sable de Taupikeau",
	"Dondozo Whisker": "Barbillon d'Oyacata",
	"Veluza Fillet": "Chair de Délestin",
	"Finizen Mucus": "Mucus de Dofin",
	"Smoliv Oil": "Huile d'Olivini",
	"Capsakid Seed": "Graine de Pimito",
	"Tadbulb Mucus": "Mucus de Têtampoule",
	"Varoom Fume": "Gaz de Vrombi",
	"Orthworm Tarnish": "Rouille de Ferdeter",
	"Tandemaus Fur": "Poils de Compagnol",
	"Cetoddle Grease": "Graisse de Piétacé",
	"Frigibax Scales": "Écaille de Frigodo",
	"Tatsugiri Scales": "Écaille de Nigirigon",
	"Cyclizar Scales": "Écaille de Motorizard",
	"Pawmi Fur": "Poils de Pohm",
	"Wattrel Feather": "Plume de Zapétrel",
	"Bombirdier Feather": "Plume de Lestombaile",
	"Squawkabilly Feather": "Plume de Tapatoès",
	"Flamigo Down": "Duvet de Flamenroule",
	"Klawf Claw": "Pince de Craparoi",
	"Nacli Salt": "Sel de Selutin",
	"Glimmet Crystal": "Cristal de Germéclat",
	"Shroodle Ink": "Encre de Gribouraigne",
	"Fidough Fur": "Poils de Pâtachiot",
	"Maschiff Fang": "Croc de Grondogue",
	"Bramblin Twig": "Branche de Virovent",
	"Gimmighoul Coin": "Pièce de Mordudor",
	"Tinkatink Hair": "Poils de Forgerette",
	"Charcadet Soot": "Suie de Charbambin",
	"Toedscool Flaps": "Membrane de Terracool",
	"Wooper Slime": "Mucus d'Axoloto",
	"TM100": "CT100",
	"TM101": "CT101",
	"TM102": "CT102",
	"TM103": "CT103",
	"TM104": "CT104",
	"TM105": "CT105",
	"TM106": "CT106",
	"TM107": "CT107",
	"TM108": "CT108",
	"TM109": "CT109",
	"TM110": "CT110",
	"TM111": "CT111",
	"TM112": "CT112",
	"TM113": "CT113",
	"TM114": "CT114",
	"TM115": "CT115",
	"TM116": "CT116",
	"TM117": "CT117",
	"TM118": "CT118",
	"TM119": "CT119",
	"TM120": "CT120",
	"TM121": "CT121",
	"TM122": "CT122",
	"TM123": "CT123",
	"TM124": "CT124",
	"TM125": "CT125",
	"TM126": "CT126",
	"TM127": "CT127",
	"TM128": "CT128",
	"TM129": "CT129",
	"TM130": "CT130",
	"TM131": "CT131",
	"TM132": "CT132",
	"TM133": "CT133",
	"TM134": "CT134",
	"TM135": "CT135",
	"TM136": "CT136",
	"TM137": "CT137",
	"TM138": "CT138",
	"TM139": "CT139",
	"TM140": "CT140",
	"TM141": "CT141",
	"TM142": "CT142",
	"TM143": "CT143",
	"TM144": "CT144",
	"TM145": "CT145",
	"TM146": "CT146",
	"TM147": "CT147",
	"TM148": "CT148",
	"TM149": "CT149",
	"TM150": "CT150",
	"TM151": "CT151",
	"TM152": "CT152",
	"TM153": "CT153",
	"TM154": "CT154",
	"TM155": "CT155",
	"TM156": "CT156",
	"TM157": "CT157",
	"TM158": "CT158",
	"TM159": "CT159",
	"TM160": "CT160",
	"TM161": "CT161",
	"TM162": "CT162",
	"TM163": "CT163",
	"TM164": "CT164",
	"TM165": "CT165",
	"TM166": "CT166",
	"TM167": "CT167",
	"TM168": "CT168",
	"TM169": "CT169",
	"TM170": "CT170",
	"TM171": "CT171",
	"Picnic Set": "Set de Pique-Nique",
	"Academy Bottle": "Gourde de l'Académie",
	"Academy Bottle": "Gourde de l'Académie",
	"Polka-Dot Bottle": "Gourde à Pois",
	"Striped Bottle": "Gourde à Rayures",
	"Diamond Bottle": "Gourde à Losanges",
	"Academy Cup": "Tasse de l'Académie",
	"Academy Cup": "Tasse de l'Académie",
	"Striped Cup": "Tasse à Rayures Jaunes",
	"Polka-Dot Cup": "Tasse à Pois",
	"Flower Pattern Cup": "Tasse à Fleurs",
	"Academy Tablecloth": "Nappe de l'Académie",
	"Academy Tablecloth": "Nappe de l'Académie",
	"Whimsical Tablecloth": "Nappe Fantaisie",
	"Leafy Tablecloth": "Nappe Verdoyante",
	"Spooky Tablecloth": "Nappe Hantée",
	"Academy Ball": "Ballon de l'Académie",
	"Academy Ball": "Ballon de l'Académie",
	"Marill Ball": "Ballon Marill",
	"Yarn Ball": "Pelote de Laine",
	"Cyber Ball": "Ballon Gaming",
	"Gold Pick": "Pique Dorée",
	"Silver Pick": "Pique Argentée",
	"Red-Flag Pick": "Pique à Fanion Rouge",
	"Blue-Flag Pick": "Pique à Fanion Bleu",
	"Pika-Pika Pick": "Pique Pikapika",
	"Winking Pika Pick": "Pique à Chu Fripon",
	"Vee-Vee Pick": "Pique Volivoli",
	"Smiling Vee Pick": "Pique Évo Rit",
	"Blue Poké Ball Pick": "Pique à Ball Bleue",
	"Auspicious Armor": "Armure de la Fortune",
	"Leader's Crest": "Emblème du Général",
	"Pink Bottle": "Gourde Rose",
	"Blue Bottle": "Gourde Bleue",
	"Yellow Bottle": "Gourde Jaune",
	"Steel Bottle (R)": "Gourde Inox (Rouge)",
	"Steel Bottle (Y)": "Gourde Inox (Jaune)",
	"Steel Bottle (B)": "Gourde Inox (Bleu)",
	"Silver Bottle": "Gourde Titane (Argent)",
	"Barred Cup": "Tasse à Rayures Bleues",
	"Diamond Pattern Cup": "Tasse à Losanges",
	"Fire Pattern Cup": "Tasse à Flammes",
	"Pink Cup": "Tasse Rose",
	"Blue Cup": "Tasse Bleue",
	"Yellow Cup": "Tasse Jaune",
	"Pikachu Cup": "Tasse Pikachu",
	"Eevee Cup": "Tasse Évoli",
	"Slowpoke Cup": "Tasse Ramoloss",
	"Silver Cup": "Tasse Titane (Argent)",
	"Exercise Ball": "Ballon d'Exercice",
	"Plaid Tablecloth (Y)": "Nappe Tartan Jaune",
	"Plaid Tablecloth (B)": "Nappe Tartan Bleue",
	"Plaid Tablecloth (R)": "Nappe Tartan Rouge",
	"B&W Grass Tablecloth": "Nappe Hautes Herbes",
	"Battle Tablecloth": "Nappe Combat Pokémon",
	"Monstrous Tablecloth": "Nappe Kaiju",
	"Striped Tablecloth": "Nappe à Rayures",
	"Diamond Tablecloth": "Nappe à Losanges",
	"Polka-Dot Tablecloth": "Nappe à Pois",
	"Lilac Tablecloth": "Nappe Mauve",
	"Mint Tablecloth": "Nappe Menthe",
	"Peach Tablecloth": "Nappe Beige",
	"Yellow Tablecloth": "Nappe Jaune",
	"Blue Tablecloth": "Nappe Bleue",
	"Pink Tablecloth": "Nappe Rose",
	"Gold Bottle": "Gourde Titane (Or)",
	"Bronze Bottle": "Gourde Titane (Bronze)",
	"Gold Cup": "Tasse Titane (Or)",
	"Bronze Cup": "Tasse Titane (Bronze)",
	"Green Poké Ball Pick": "Pique à Ball Verte",
	"Red Poké Ball Pick": "Pique à Ball Rouge",
	"Party Sparkler Pick": "Pique Feu d'Artifice",
	"Heroic Sword Pick": "Pique Épée du Héros",
	"Magical Star Pick": "Pique Étoile Magique",
	"Magical Heart Pick": "Pique Cœur Magique",
	"Parasol Pick": "Pique Parasol",
	"Blue-Sky Flower Pick": "Pique Fleur d'Azur",
	"Sunset Flower Pick": "Pique Fleur du Ponant",
	"Sunrise Flower Pick": "Pique Fleur du Levant",
	"Blue Dish": "Assiette Bleue",
	"Green Dish": "Assiette Verte",
	"Orange Dish": "Assiette Orange",
	"Red Dish": "Assiette Rouge",
	"White Dish": "Assiette Blanche",
	"Yellow Dish": "Assiette Jaune"
}